eucalyptus/eucaconsole

- eucaconsole/static/js/pages/instance_launch.js
- eucaconsole/static/js/pages/launchconfig_wizard.js
- eucaconsole/static/js/widgets/securitygroup_rules.js
https://eucalyptus.atlassian.net/browse/GUI-1534
> GUI-1534 Adjust the VPC network display to reflect the correct VPC value when the create security group modal is re-opened.

- eucaconsole/templates/dialogs/volume_dialogs.pt
- eucaconsole/templates/instances/instance_volumes.pt
remove placeholder text for attach dialog shown from volumes pages
https://eucalyptus.atlassian.net/browse/GUI-1517
> GUI-1517 remove placeholder text for attach dialog shown from volumes pages

- eucaconsole/views/instances.py
fixed logic for removing role filter in instances landing page
https://eucalyptus.atlassian.net/browse/GUI-1119
> GUI-1119 fixed logic for removing role filter in instances landing page

- COPYING
- README.rst
This commit adds a short blurb about code contributions and licensing to README.rst.  I added the third sentence at Legal's request; for the remainder I am happy to discuss wording and which section it should go into.
I also updated the date range in the COPYING file.
> Add brief info about contributing to README.rst

- eucaconsole/templates/instances/instance_launch_more.pt
- eucaconsole/views/instances.py
don't show addressing mode on launch_more when logged into AWS. enforce public  in code
https://eucalyptus.atlassian.net/browse/GUI-1541
> GUI-1541 don't show addressing mode on launch_more when logged into AWS. enforce public  in code

- eucaconsole/views/users.py
allow generate_keys call to work with minimal IAM perms
https://eucalyptus.atlassian.net/browse/GUI-252
> GUI-252 allow generate_keys call to work with minimal IAM perms

- eucaconsole/views/__init__.py
specify unicode for resource name formatting
https://eucalyptus.atlassian.net/browse/GUI-1558
> GUI-1558 specify unicode for resource name formatting

- eucaconsole/views/instances.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-1576
Heads up: Do not merge unless GUI-1576 has been scoped for 4.1
> GUI-1576: Filter volumes by the instance's availability zone on the instance detail page's Volumes tab

- eucaconsole/views/buckets.py
- tests/buckets/test_buckets.py
https://eucalyptus.atlassian.net/browse/GUI-1536
> GUI 1536 replace default subpath when it might contain lost path information

- eucaconsole/static/js/widgets/policy_list.js
check for error message before alerting user since navigating away is OK
https://eucalyptus.atlassian.net/browse/GUI-1494
> GUI-1494 check for error message before alerting user since navigating away is OK

- eucaconsole/views/dashboard.py
include only running instances in scaling group total
https://eucalyptus.atlassian.net/browse/GUI-1594
> GUI-1594 include only running instances in scaling group total

- eucaconsole/templates/policies/policy_generator.pt
Fixes https://eucalyptus.atlassian.net/browse/GUI-1588
> GUI-1588: Add missing check in policy generator to limit to deny-only policies for accounts

- eucaconsole/static/js/pages/landingpage.js
- eucaconsole/views/__init__.py
improving detection of permission denial API responses
https://eucalyptus.atlassian.net/browse/GUI-1589
> GUI-1589 improving detection of permission denial API responses

- eucaconsole/forms/keypairs.py
- eucaconsole/routes.py
- eucaconsole/templates/dashboard.pt
- eucaconsole/templates/instances/instance_view.pt
- eucaconsole/templates/keypairs/keypair_view.pt
- eucaconsole/templates/keypairs/keypairs.pt
- eucaconsole/templates/launchconfigs/launchconfig_view.pt
- eucaconsole/views/keypairs.py
https://eucalyptus.atlassian.net/browse/GUI-1524
> Gui 1524 allow more characters in keypair name

- eucaconsole/static/js/pages/instance_launch.js
restore submit button if create call errors out
https://eucalyptus.atlassian.net/browse/GUI-1563
> GUI-1563 restore submit button if create call errors out

- eucaconsole/forms/scalinggroups.py
- eucaconsole/static/js/jasmine-spec/spec_scalinggroup.js
- eucaconsole/static/js/pages/scalinggroup.js
- eucaconsole/templates/scalinggroups/scalinggroup_view.pt
- eucaconsole/views/scalinggroups.py
https://eucalyptus.atlassian.net/browse/GUI-1533
> GUI-1533 Preserve the order of the termination policy options on the scaling group detail page

- eucaconsole/views/scalinggroups.py
- tests/scalinggroups/test_scalinggroups.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-1581
> GUI-1581: Return 404 instead of 500 if scaling group lookup fails

- eucaconsole/static/js/widgets/bdmapping_editor.js
- eucaconsole/templates/panels/bdmapping_editor.pt
disallow adding new device with conflicting device name
https://eucalyptus.atlassian.net/browse/GUI-1583
> GUI-1583 disallow adding new device with conflicting device name

- eucaconsole/static/js/jasmine-spec/spec_instance_launch.js
- eucaconsole/static/js/jasmine-spec/spec_launchconfig_wizard.js
- eucaconsole/static/js/pages/instance_launch.js
- eucaconsole/static/js/pages/launchconfig_wizard.js
https://eucalyptus.atlassian.net/browse/GUI-1605
> GUI 1605 - When security group field gets cleared on launch config and instance launch wizards, set securityGroups to empty, []

- eucaconsole/static/html/help/console_bucket_detail.html
Please review and merge with maint-4.1 branch for 4.1.1. Thanks!
> DOC-1530: updated bucket details help page.

- eucaconsole/routes.py
- eucaconsole/static/css/pages/dashboard.css
- eucaconsole/static/css/pages/stack.css
- eucaconsole/static/js/pages/stack.js
- eucaconsole/static/sass/pages/dashboard.scss
- eucaconsole/static/sass/pages/stack.scss
- eucaconsole/templates/dashboard.pt
- eucaconsole/templates/stacks/stack_view.pt
- eucaconsole/views/dashboard.py
- eucaconsole/views/stacks.py
https://eucalyptus.atlassian.net/browse/GUI-1489
> GUI-1489 Stack detail page complete. UX tweaks needed

- eucaconsole/routes.py
- eucaconsole/static/css/eucaconsole.css
- eucaconsole/static/sass/eucaconsole.scss
- eucaconsole/templates/master_layout.pt
- eucaconsole/templates/panels/top_nav.pt
updated navigation to always use hamburger
https://eucalyptus.atlassian.net/browse/GUI-1474
> GUI-1474 updated navigation to always use hamburger

- tests/selenium/Selenium_RC_Plugins/user-extensions.js
https://eucalyptus.atlassian.net/browse/GUI-1606
> Added a condition to storeTextIfPresent to indicate failure to find locator without failing the test.

- tests/selenium/Selenium_RC_Plugins/user-extensions.js
https://eucalyptus.atlassian.net/browse/GUI-1626
> Fix to prevent storeTextIfPresent failing

- eucaconsole/static/js/pages/instance_launch.js
Fixes https://eucalyptus.atlassian.net/browse/GUI-1623
> GUI-1623: Update tags list in summary area of launch instance wizard when a tag is added or removed

- eucaconsole/static/css/widgets/image_picker.css
- eucaconsole/static/sass/widgets/image_picker.scss
Fixes https://eucalyptus.atlassian.net/browse/GUI-1607
> GUI-1607: Fix alignment of magic search bar placeholder text in image picker on launch wizards

- eucaconsole/static/html/help/about-the-team.html
Fixes https://eucalyptus.atlassian.net/browse/GUI-1629
> GUI-1629: Prevent CSP violations by removing unneeded JS on the About the Team page

- eucaconsole/models/quotas.py
- eucaconsole/views/users.py
ensure we only pass DelegateAccount to API calls when it is set
https://eucalyptus.atlassian.net/browse/GUI-1609
> GUI-1609 ensure we only pass DelegateAccount to API calls when it is set

- eucaconsole/caches.py
obfuscate cache key
https://eucalyptus.atlassian.net/browse/GUI-1601
> GUI-1601 obfuscate cache key

- eucaconsole/forms/volumes.py
- eucaconsole/views/volumes.py
- tests/volumes/test_volumes.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-1518
> GUI-1518: Fix attaching volume to instance on volumes landing page

- eucaconsole/views/scalinggroups.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-1581
> GUI-1581: Prevent 500 error when scaling group lookup fails on detail pages

- eucaconsole/templates/policies/policy_generator.pt
Potential improvements for https://eucalyptus.atlassian.net/browse/GUI-1457
> GUI-1457: Optimize load time of IAM Policy Generator by leveraging Angular's bind once syntax

- eucaconsole/static/js/pages/iam_policy_wizard.js
Fixes https://eucalyptus.atlassian.net/browse/GUI-1624
> GUI-1624: Avoid canned policy XHR fetch when custom policy type is selected

- eucaconsole/static/js/pages/eucaconsole_utils.js
- eucaconsole/static/js/pages/user_view.js
- eucaconsole/static/js/widgets/policy_list.js
- eucaconsole/templates/master_layout.pt
handle navigating away while page populating via XHR (on user_view) without error alert. Change copyright in footer
> GUI-1494, GUI-1645

- eucaconsole/views/__init__.py
- eucaconsole/views/buckets.py
- tests/buckets/test_buckets.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-1647
> GUI-1647: Support unicode characters in S3 folder names

- eucaconsole/static/html/help/console_create_stack.html
- eucaconsole/static/html/help/console_stack_detail_general.html
Please merge approved content for stack pages.
> DOC-1553: new console help topics for stack pages.

- eucaconsole/templates/instances/instance_launch.pt
- eucaconsole/templates/instances/instance_launch_more.pt
- eucaconsole/templates/instances/instance_view.pt
- eucaconsole/templates/launchconfigs/launchconfig_wizard.pt
fixed input tags to be proper html
https://eucalyptus.atlassian.net/browse/GUI-1675
> GUI-1675 fixed input tags to be proper html

- Gruntfile.js
- package.json
added 'grunt compass' task for one-time sass processing. Added compass to 'grunt watch' task for functionality like 'make watch'
https://eucalyptus.atlassian.net/browse/GUI-1416
> GUI-1416 added 'grunt compass' task for one-time sass processing. updated watch task

- .travis.yml
- README.rst
- eucaconsole/views/__init__.py
- eucaconsole/views/buckets.py
- eucaconsole/views/snapshots.py
- eucaconsole/views/volumes.py
- setup.py
- tests/__init__.py
- tests/auth/test_changepassword.py
- tests/auth/test_login.py
- tests/buckets/test_buckets.py
- tests/snapshots/test_snapshots.py
- tests/volumes/test_volumes.py
References https://eucalyptus.atlassian.net/browse/GUI-1417
> GUI-1417: Moto-based unit tests for storage-related views (S3, volumes, snapshots)

- eucaconsole/static/js/pages/elb.js
- eucaconsole/static/js/pages/elbs.js
- eucaconsole/templates/dialogs/elb_dialogs.pt
cleaned up delete dialog, matches wireframe, fixed wobbly busy
https://eucalyptus.atlassian.net/browse/GUI-1485
looks good on FF and Chrome (OS X)
> GUI-1485 cleaned up delete dialog, matches wireframe, fixed wobbly busy

- eucaconsole/static/js/jasmine-spec/spec_bucket_contents.js
- eucaconsole/static/js/pages/bucket_contents.js
- eucaconsole/static/js/pages/buckets.js
- eucaconsole/views/buckets.py
simplified server-side object delete using bucket.delete_keys()
https://eucalyptus.atlassian.net/browse/GUI-1679
> GUI-1679 simplified server-side object delete using bucket.delete_keys()

- eucaconsole/static/js/pages/image.js
- eucaconsole/templates/images/image_view.pt
Fixes https://eucalyptus.atlassian.net/browse/GUI-1682
> GUI-1682: Fix brittle implementation in sharing panel on image detail page

- eucaconsole/forms/instances.py
- eucaconsole/static/js/jasmine-spec/spec_instances.js
- eucaconsole/static/js/pages/instances.js
- eucaconsole/templates/dialogs/instance_dialogs.pt
- eucaconsole/templates/instances/instances.pt
- eucaconsole/views/instances.py
https://eucalyptus.atlassian.net/browse/GUI-1539
> GUI-1539 on AWS, display only the same network elastic IPs for selections on the associate IP dialog

- eucaconsole/static/css/widgets/securitygroup_rules.css
- eucaconsole/static/sass/widgets/securitygroup_rules.scss
- eucaconsole/templates/panels/securitygroup_rules.pt
https://eucalyptus.atlassian.net/browse/GUI-1684
> Gui 1684 Adjusted the security group rule panel's style

- eucaconsole/templates/buckets/bucket_contents.pt
- eucaconsole/templates/buckets/buckets.pt
- eucaconsole/templates/cloudwatch/alarms.pt
- eucaconsole/templates/elbs/elbs.pt
- eucaconsole/templates/images/images.pt
- eucaconsole/templates/ipaddresses/ipaddresses.pt
- eucaconsole/templates/keypairs/keypairs.pt
- eucaconsole/templates/launchconfigs/launchconfigs.pt
- eucaconsole/templates/macros.pt
- eucaconsole/templates/panels/autoscale_tag_editor.pt
- eucaconsole/templates/panels/bdmapping_editor.pt
- eucaconsole/templates/panels/image_picker.pt
- eucaconsole/templates/panels/policy_list.pt
- eucaconsole/templates/panels/s3_metadata_editor.pt
- eucaconsole/templates/panels/s3_sharing_panel.pt
- eucaconsole/templates/panels/securitygroup_rules.pt
- eucaconsole/templates/panels/tag_editor.pt
- eucaconsole/templates/panels/user_editor.pt
- eucaconsole/templates/scalinggroups/scalinggroups.pt
- eucaconsole/templates/securitygroups/securitygroups.pt
- eucaconsole/templates/stacks/stack_view.pt
- eucaconsole/templates/stacks/stacks.pt
Fixes https://eucalyptus.atlassian.net/browse/GUI-1702
> GUI-1702: Remove unnecessary ng-app attributes

- eucaconsole/templates/accounts/accounts.pt
- eucaconsole/templates/buckets/bucket_contents.pt
- eucaconsole/templates/buckets/buckets.pt
- eucaconsole/templates/cloudwatch/alarms.pt
- eucaconsole/templates/elbs/elbs.pt
- eucaconsole/templates/groups/groups.pt
- eucaconsole/templates/images/images.pt
- eucaconsole/templates/instances/instances.pt
- eucaconsole/templates/ipaddresses/ipaddresses.pt
- eucaconsole/templates/keypairs/keypairs.pt
- eucaconsole/templates/launchconfigs/launchconfigs.pt
- eucaconsole/templates/panels/securitygroup_rules.pt
- eucaconsole/templates/roles/roles.pt
- eucaconsole/templates/scalinggroups/scalinggroups.pt
- eucaconsole/templates/securitygroups/securitygroups.pt
- eucaconsole/templates/snapshots/snapshots.pt
- eucaconsole/templates/stacks/stacks.pt
- eucaconsole/templates/users/users.pt
- eucaconsole/templates/volumes/volumes.pt
https://eucalyptus.atlassian.net/browse/GUI-1729
> GUI-1729: Removed custom_filters.js script tags in the templates

- eucaconsole/static/css/pages/volume.css
- eucaconsole/static/js/pages/volume.js
- eucaconsole/static/sass/pages/volume.scss
- eucaconsole/templates/volumes/volume_view.pt
Fixes https://eucalyptus.atlassian.net/browse/GUI-1735
Fixes recurring Jenkins failure on create volume page's zone selector
> GUI-1735: Convert Availability Zone selector from Chosen widget to standard drop-down on create volume page

- eucaconsole/forms/elbs.py
- eucaconsole/forms/instances.py
- eucaconsole/forms/launchconfigs.py
- eucaconsole/forms/scalinggroups.py
- eucaconsole/templates/elbs/elb_wizard.pt
- eucaconsole/templates/instances/instance_create_image.pt
- eucaconsole/templates/instances/instance_launch.pt
- eucaconsole/templates/instances/instance_launch_more.pt
- eucaconsole/templates/instances/instance_view.pt
- eucaconsole/templates/launchconfigs/launchconfig_wizard.pt
- eucaconsole/templates/panels/form_field_row.pt
- eucaconsole/templates/stacks/stack_wizard.pt
Also set 16K char maxlength in userdata textareas.
Fixes https://eucalyptus.atlassian.net/browse/GUI-1728
> GUI-1728: Ensure form field help text/icons are implemented consistently across the app

- eucaconsole/static/css/pages/stack_wizard.css
- eucaconsole/static/js/pages/instance_launch.js
- eucaconsole/static/js/pages/stack_wizard.js
- eucaconsole/static/sass/pages/stack_wizard.scss
- eucaconsole/templates/instances/instance_launch.pt
- eucaconsole/templates/stacks/stack_view.pt
- eucaconsole/templates/stacks/stack_wizard.pt
- eucaconsole/views/stacks.py
converted param and sample stack selectors from chosen to normal
https://eucalyptus.atlassian.net/browse/GUI-1711
https://eucalyptus.atlassian.net/browse/GUI-1733
> GUI-1733, GUI-1711 converted param and sample stack selectors from chosen to normal

- eucaconsole/templates/panels/top_nav.pt
https://eucalyptus.atlassian.net/browse/GUI-1753
> GUI -1753: Fixed ids of cloudformation and stacks menuitems in the nav menu

- eucaconsole/static/js/pages/stack_wizard.js
- eucaconsole/templates/stacks/stack_wizard.pt
prune hidden form elements from params section
https://eucalyptus.atlassian.net/browse/GUI-1771
> GUI-1771 prune hidden form elements from params section

- eucaconsole/static/css/pages/cloudwatch_charts.css
- eucaconsole/static/sass/pages/cloudwatch_charts.scss
Implements https://eucalyptus.atlassian.net/browse/GUI-1757
> GUI-1757: Add dots to data points in CloudWatch time-series line charts

- eucaconsole/templates/volumes/volumes.pt
Fixes https://eucalyptus.atlassian.net/browse/GUI-1760
> GUI-1760: Show "Detach from instance" action on volumes landing page for attached volumes

- eucaconsole/templates/dialogs/create_folder_dialog.pt
- eucaconsole/templates/panels/form_field_row.pt
- eucaconsole/templates/volumes/volume_snapshots.pt
Fixes:
https://eucalyptus.atlassian.net/browse/GUI-1677
https://eucalyptus.atlassian.net/browse/GUI-1775
> GUI-1677: Stack label above input in create folder dialog to avoid obscuring label

- eucaconsole/views/dashboard.py
use same stack list as landing page to generate tota
https://eucalyptus.atlassian.net/browse/GUI-1784
> GUI-1784 use same stack list as landing page to generate tota

- eucaconsole/static/css/pages/stack.css
- eucaconsole/static/js/pages/stack.js
- eucaconsole/static/js/widgets/policy_list.js
- eucaconsole/static/sass/pages/stack.scss
- eucaconsole/templates/stacks/stack_view.pt
- eucaconsole/views/stacks.py
https://eucalyptus.atlassian.net/browse/GUI-1725
tested in Chrome and FF (latest) on OS X
> Gui 1725 show stack template in a modal

- README.rst
- setup.py
https://eucalyptus.atlassian.net/browse/GUI-1699
> GUI-1699 update boto to 2.38

- eucaconsole/static/css/eucaconsole.css
- eucaconsole/static/sass/eucaconsole.scss
- eucaconsole/static/sass/includes/_eucavariables.scss
https://eucalyptus.atlassian.net/browse/GUI-1763
> GUI-1763: Update breadcrumb separator

- eucaconsole/static/css/pages/elb_wizard.css
- eucaconsole/static/css/pages/instance_launch.css
- eucaconsole/static/css/pages/launchconfig_wizard.css
- eucaconsole/static/css/pages/scalinggroup_wizard.css
- eucaconsole/static/css/pages/stack_wizard.css
- eucaconsole/static/js/widgets/tag_editor.js
- eucaconsole/static/sass/includes/_wizard.scss
- eucaconsole/templates/instances/instance_launch.pt
- eucaconsole/templates/panels/form_field_row.pt
Fixes:
https://eucalyptus.atlassian.net/browse/GUI-1767
https://eucalyptus.atlassian.net/browse/GUI-1774
> GUI-1767, GUI-1774: Fix alignment of labels/fields on launch instance wizard

- eucaconsole/models/auth.py
- setup.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-1772
> GUI-1772: Safer XML parsing

- setup.py
https://eucalyptus.atlassian.net/browse/GUI-1820
> GUI-1820: Safer pinning of defusedxml version

- eucaconsole/views/roles.py
added additional check in case instance profile has no role(s)
https://eucalyptus.atlassian.net/browse/GUI-1821
> GUI-1821 added additional check in case instance profile has no role(s)

- eucaconsole/forms/quotas.py
- eucaconsole/models/quotas.py
- eucaconsole/templates/users/quotas.pt
added new instance quotas
https://eucalyptus.atlassian.net/browse/GUI-1644
> GUI-1644 added new instance quotas

- eucaconsole/forms/elbs.py
- eucaconsole/static/js/pages/elb_wizard.js
- eucaconsole/templates/dialogs/select_certificate_dialog.pt
- eucaconsole/templates/elbs/elb_wizard.pt
- eucaconsole/views/dialogs.py
- eucaconsole/views/elbs.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-1828
> GUI-1828: Prevent unexpected logout on Create ELB wizard when IAM policy prevents listing of certificates

- eucaconsole/config.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-1835
> GUI-1835: PEP8 and typo fixes for clchost/clcport deprecation warning

- eucaconsole/static/js/pages/stack_wizard.js
- eucaconsole/templates/stacks/stack_wizard.pt
- eucaconsole/views/stacks.py
https://eucalyptus.atlassian.net/browse/GUI-1834
> GUI-1834 Added client and server side checks for template size

- eucaconsole/views/__init__.py
- eucaconsole/views/managecredentials.py
re-factored code for getting clchost/port settings, works for login now
https://eucalyptus.atlassian.net/browse/GUI-1795
> GUI-1795 re-factored code for getting clchost/port settings, works for login now

- eucaconsole/views/roles.py
> Maint 4.1 merge

- setup.py
modified boto version requirement to require >=2.34
> GUI-1839 update boto required version

- eucaconsole/static/js/widgets/instance_selector.js
Includes fixes for:
- https://eucalyptus.atlassian.net/browse/GUI-1804
- https://eucalyptus.atlassian.net/browse/GUI-1845
> GUI-1804, GUI-1845: ELB instance selector fixes

- eucaconsole/views/instances.py
- eucaconsole/views/roles.py
fixed 2 places that needed additional checks with CLI users deletes role without removing instance profile
https://eucalyptus.atlassian.net/browse/GUI-1856
> GUI-1856 fixed 2 places that needed additional checks with CLI users deletes role without removing instance profile

- eucaconsole/views/launchconfigs.py
ensure filter list for DescribeImages contains list of unique ids
https://eucalyptus.atlassian.net/browse/GUI-1846
> GUI-1846 ensure filter list for DescribeImages contains list of unique ids

- eucaconsole/views/dashboard.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-1862
> GUI-1862: Prevent 500 error when loading dashboard on AWS

- eucaconsole/static/js/pages/cloudwatch_charts.js
Fixes https://eucalyptus.atlassian.net/browse/GUI-1833
> GUI-1833: Fix attribute lookup to enable detailed charts to display on ELB Monitoring page

- eucaconsole/static/js/pages/bucket_contents.js
only add prefix + / if prefix is not empty string
https://eucalyptus.atlassian.net/browse/GUI-1841
> GUI-1841 fix delete object from top level of bucket

- eucaconsole/templates/login.pt
- eucaconsole/views/login.py
added meta refresh tag to reload page every 29 minutes
https://eucalyptus.atlassian.net/browse/GUI-1146
> GUI-1146 added meta refresh tag to reload page every 29 minutes

- eucaconsole/templates/elbs/elb_wizard.pt
- eucaconsole/views/elbs.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-1840
> GUI-1840: Preconfigure HTTP port 80 listener in Create ELB Wizard

- eucaconsole/static/css/pages/instances.css
- eucaconsole/static/sass/pages/instances.scss
Fixes https://eucalyptus.atlassian.net/browse/GUI-1545
> GUI-1545: Add extra bottom padding on instances landing page to avoid cutting off actions menu in table view

- eucaconsole/views/buckets.py
- tests/buckets/test_buckets.py
fix case where folder name appears in bucket name
https://eucalyptus.atlassian.net/browse/GUI-1872
> GUI-1872 fix case where folder name appears in bucket name

- eucaconsole/static/js/pages/bucket_contents.js
- eucaconsole/views/buckets.py
improved error reporting when deleting keys
https://eucalyptus.atlassian.net/browse/GUI-1853
> GUI-1853 improved error reporting when deleting keys

- eucaconsole/static/js/pages/stack_wizard.js
- eucaconsole/templates/instances/instance_launch.pt
- eucaconsole/templates/launchconfigs/launchconfig_wizard.pt
- eucaconsole/templates/scalinggroups/scalinggroup_wizard.pt
- eucaconsole/templates/stacks/stack_wizard.pt
https://eucalyptus.atlassian.net/browse/GUI-1764
https://eucalyptus.atlassian.net/browse/GUI-1777
> GUI 1764 disable 2nd tab by default and provide busy indicator for stack create

- eucaconsole/forms/__init__.py
- eucaconsole/views/stacks.py
set location so that error returns to a page that loads
https://eucalyptus.atlassian.net/browse/GUI-1754
> GUI-1754 set location so that error returns to a page that loads

- eucaconsole/static/css/pages/instances.css
- eucaconsole/static/js/pages/stacks.js
- eucaconsole/static/sass/pages/instances.scss
- eucaconsole/templates/dialogs/stack_dialogs.pt
- eucaconsole/templates/stacks/stacks.pt
- eucaconsole/views/stacks.py
https://eucalyptus.atlassian.net/browse/GUI-1801
> GUI 1801 converted landing page delete operation to XHR, added 1 second delay for table refresh

- eucaconsole/static/js/jasmine-spec/spec_iam_policy_wizard.js
- eucaconsole/static/js/pages/iam_policy_wizard.js
- eucaconsole/templates/policies/policy_generator.pt
Fixes https://eucalyptus.atlassian.net/browse/GUI-1802 and *significantly* improves the load time of the IAM Policy Generator
> GUI-1802: IAM Policy Generator speedups

- eucaconsole/static/css/pages/elb.css
- eucaconsole/static/css/widgets/instance_selector.css
- eucaconsole/static/html/directives/instance_selector.html
- eucaconsole/static/js/pages/elb_instances.js
- eucaconsole/static/js/pages/elb_wizard.js
- eucaconsole/static/js/widgets/instance_selector.js
- eucaconsole/static/sass/pages/elb.scss
- eucaconsole/static/sass/widgets/instance_selector.scss
- eucaconsole/templates/elbs/elb_instances.pt
Implements:
- https://eucalyptus.atlassian.net/browse/GUI-1805
- https://eucalyptus.atlassian.net/browse/GUI-1822
> GUI-1805, GUI-1822: ELB Detail Page - Instance selector improvements

- eucaconsole/views/__init__.py
- eucaconsole/views/buckets.py
- eucaconsole/views/dashboard.py
Fixes: 
https://eucalyptus.atlassian.net/browse/GUI-1886
https://eucalyptus.atlassian.net/browse/GUI-1887
> GUI-1886, GUI-1887: Refactor shared buckets storage key lookup to avoid 500 errors on S3 buckets landing page and object details page

- eucaconsole/static/css/pages/login.css
- eucaconsole/static/sass/pages/login.scss
- eucaconsole/templates/login.pt
Fixes whitespace issues and wrapping of tab titles on login page.
https://eucalyptus.atlassian.net/browse/GUI-1706
https://eucalyptus.atlassian.net/browse/GUI-1800
> GUI-1706, GUI-1800: Fix whitespace/wrapping issues on login page

- eucaconsole/static/html/help/console_create_stack.html
- eucaconsole/static/html/help/console_stack_detail_general.html
Please add new changes to help pages.
> DOC-1611: updated stack help topics to comply with new changes.

- eucaconsole/static/js/pages/launchconfig_wizard.js
reverted change from PR#1076
https://github.com/eucalyptus/eucaconsole/pull/1076/files
https://eucalyptus.atlassian.net/browse/GUI-1896
> GUI-1896 reverted change from PR#1076

- eucaconsole/forms/__init__.py
- eucaconsole/forms/elbs.py
- eucaconsole/forms/instances.py
- eucaconsole/forms/launchconfigs.py
- eucaconsole/forms/scalinggroups.py
- eucaconsole/forms/securitygroups.py
- eucaconsole/forms/volumes.py
- eucaconsole/static/css/eucaconsole.css
- eucaconsole/static/css/pages/instance_launch.css
- eucaconsole/static/css/pages/instance_launch_more.css
- eucaconsole/static/css/pages/launchconfig_wizard.css
- eucaconsole/static/js/pages/instance_launch.js
- eucaconsole/static/js/pages/launchconfig_wizard.js
- eucaconsole/static/sass/eucaconsole.scss
- eucaconsole/static/sass/includes/_eucavariables.scss
- eucaconsole/static/sass/pages/instance_launch.scss
- eucaconsole/static/sass/pages/instance_launch_more.scss
- eucaconsole/static/sass/pages/launchconfig_wizard.scss
- eucaconsole/templates/instances/instance_launch.pt
- eucaconsole/templates/instances/instance_launch_more.pt
- eucaconsole/templates/launchconfigs/launchconfig_create_more.pt
- eucaconsole/templates/launchconfigs/launchconfig_wizard.pt
- eucaconsole/views/instances.py
Implements https://eucalyptus.atlassian.net/browse/GUI-1577
Also fixes https://eucalyptus.atlassian.net/browse/GUI-1859 and includes misc PEP8 fixes
> GUI-1577, GUI-1859: More specific labels and help bubbles for monitoring enabled option; fixes color of help icons inside expandos

- eucaconsole/static/css/pages/dashboard.css
- eucaconsole/static/sass/pages/dashboard.scss
changed color of dash totals
https://eucalyptus.atlassian.net/browse/GUI-1632
> GUI-1632 changed color of dash totals

- eucaconsole/templates/stacks/stack_wizard.pt
disable upload to CF when file.uploads.enabled is false
https://eucalyptus.atlassian.net/browse/GUI-1910
> GUI-1910 disable upload to CF when file.uploads.enabled is false

- eucaconsole/views/__init__.py
added ufshost to image cache key
https://eucalyptus.atlassian.net/browse/GUI-1549
> GUI-1549 added ufshost to image cache key

- eucaconsole/views/stacks.py
added additional check for resources w/o properties
https://eucalyptus.atlassian.net/browse/GUI-1909
> GUI-1909 added additional check for resources w/o properties

- tests/selenium/guiops/guitester/guitester.py
Changed browser maximize to hard coded resolution because the browser wasn't being maximized properly
> Modified browser resolution

- eucaconsole/static/js/pages/bucket_details.js
- eucaconsole/static/js/widgets/s3_sharing_panel.js
Also: minor JSHint cleanup
Fixes https://eucalyptus.atlassian.net/browse/GUI-1842
> GUI-1842: Ensure Save Changes button is enabled when propagate ACLs checkbox is checked on Firefox

- eucaconsole/views/stacks.py
- tests/stacks/test_aws_convert.py
- tests/stacks/test_template.json
added another unit test and some fixes to tested code
https://eucalyptus.atlassian.net/browse/GUI-1698
> GUI-1698 added another unit test and some fixes to tested code

- eucaconsole/static/js/pages/stack_wizard.js
- eucaconsole/templates/stacks/stack_wizard.pt
- eucaconsole/views/stacks.py
https://eucalyptus.atlassian.net/browse/GUI-1911
https://eucalyptus.atlassian.net/browse/GUI-1906
https://eucalyptus.atlassian.net/browse/GUI-1904
This includes GUI-1904 since it modifies some of the same code
> Gui 1911 removed uses of signed url in stack creation.

- eucaconsole/models/auth.py
https://eucalyptus.atlassian.net/browse/GUI-1824
> GUI-1824 updated paths for dns clouds

- eucaconsole/cf-templates/Euca Stacks/LoadBalanced AutoScaling Web Application.json
removed SSL from this template
https://eucalyptus.atlassian.net/browse/GUI-1917
> GUI-1917 removed SSL from this template

- eucaconsole/static/js/widgets/securitygroup_rules.js
add test for groups named like internal elb groups to prevent invalid warning
https://eucalyptus.atlassian.net/browse/GUI-1639
> GUI-1639 add test for groups named like internal elb groups to prevent invalid warning

- eucaconsole/static/js/pages/stack.js
- eucaconsole/templates/stacks/stack_view.pt
- eucaconsole/views/stacks.py
fixed stack delete link on secondary tabs
https://eucalyptus.atlassian.net/browse/GUI-1900
https://eucalyptus.atlassian.net/browse/GUI-1901
> GUI-1900 fixed stack delete link on secondary tabs

- eucaconsole/static/css/pages/volume.css
- eucaconsole/static/css/pages/volumes.css
- eucaconsole/static/js/pages/volume.js
- eucaconsole/static/sass/pages/volume.scss
- eucaconsole/static/sass/pages/volumes.scss
- eucaconsole/templates/volumes/volume_snapshots.pt
- eucaconsole/templates/volumes/volume_view.pt
- eucaconsole/templates/volumes/volumes.pt
- eucaconsole/views/volumes.py
- tests/selenium/guiops/pages/volume/volume_view.py
Fixes:
https://eucalyptus.atlassian.net/browse/GUI-1881
https://eucalyptus.atlassian.net/browse/GUI-1921
> GUI-1881/GUI-1921: Menu item and CSS fixes for deleted and failed volumes

- tests/selenium/guiops/pages/volume/volume_view.py
> GUI-1921: Fix CSS selector in verify_volume_status_is_deleted() Selenium test

- conf/console.default.ini
- eucaconsole/static/css/pages/stack_wizard.css
- eucaconsole/static/js/pages/stack_wizard.js
- eucaconsole/static/sass/pages/stack_wizard.scss
- eucaconsole/templates/stacks/stack_wizard.pt
- eucaconsole/views/stacks.py
https://eucalyptus.atlassian.net/browse/GUI-1904
https://eucalyptus.atlassian.net/browse/GUI-1919
> GUI-1904 added client-side url validation, switch to configurable whitelist for url checking on the serve

- eucaconsole/static/js/pages/stack_wizard.js
- eucaconsole/templates/stacks/stack_view.pt
- eucaconsole/templates/stacks/stack_wizard.pt
- eucaconsole/views/stacks.py
https://eucalyptus.atlassian.net/browse/GUI-1903
> Gui 1903 added stack-id prefix to templates after creation. added collision detection and retry for stack bucket

- eucaconsole/forms/elbs.py
- eucaconsole/templates/elbs/elb_wizard.pt
Fixes https://eucalyptus.atlassian.net/browse/GUI-1785
> GUI-1785: Update validation pattern and error message for name field in Create ELB wizard

- eucaconsole/static/css/pages/elb_wizard.css
- eucaconsole/static/css/pages/instance_launch.css
- eucaconsole/static/css/pages/launchconfig_wizard.css
- eucaconsole/static/css/pages/scalinggroup_wizard.css
- eucaconsole/static/css/pages/stack_wizard.css
- eucaconsole/static/sass/includes/_wizard.scss
- eucaconsole/templates/instances/instance_launch.pt
- eucaconsole/templates/launchconfigs/launchconfig_wizard.pt
- eucaconsole/templates/scalinggroups/scalinggroup_wizard.pt
- eucaconsole/templates/stacks/stack_wizard.pt
Fixes https://eucalyptus.atlassian.net/browse/GUI-1920
> GUI-1920: Prevent unexpected word breaks in CF create stack wizard's description output in summary area

- eucaconsole/static/js/pages/eucaconsole.js
https://eucalyptus.atlassian.net/browse/GUI-1942
> GUI 1942 use different index when setting dash icon active

- eucaconsole/views/stacks.py
provide sensible default if cloudformation.url.whitelist not in console.ini
https://eucalyptus.atlassian.net/browse/GUI-1948
> GUI-1948 provide sensible default if cloudformation.url.whitelist not in console.ini

- eucaconsole/constants/policies.py
added elb and cloudformation services to read-only iam policy
https://eucalyptus.atlassian.net/browse/GUI-1946
> GUI-1946 added elb and cloudformation services to read-only iam policy

- eucaconsole/static/js/pages/stack_wizard.js
reset param list which indicates problematic aws params
https://eucalyptus.atlassian.net/browse/GUI-1939
> GUI-1939 reset param list which indicates problematic aws params

- eucaconsole/forms/buckets.py
- eucaconsole/routes.py
- eucaconsole/static/css/pages/bucket_item_details.css
- eucaconsole/static/js/pages/bucket_item_details.js
- eucaconsole/static/sass/includes/_eucavariables.scss
- eucaconsole/static/sass/pages/bucket_item_details.scss
- eucaconsole/templates/buckets/bucket_contents.pt
- eucaconsole/templates/buckets/bucket_item_details.pt
- eucaconsole/templates/dialogs/bucket_item_shared_url_dialog.pt
- eucaconsole/templates/panels/s3_metadata_editor.pt
- eucaconsole/views/buckets.py
- eucaconsole/views/dialogs.py
- eucaconsole/views/panels.py
Implements https://eucalyptus.atlassian.net/browse/GUI-1899
> GUI-1899: Link generation and sharing improvements for S3 objects

- eucaconsole/static/js/widgets/bdmapping_editor.js
pull current mapping from modified state, not initial state when adding device
https://eucalyptus.atlassian.net/browse/GUI-1945
> GUI-1945 pull current mapping from modified state, not initial state when adding device

- eucaconsole/static/css/pages/dashboard.css
- eucaconsole/static/sass/pages/dashboard.scss
totals now underline when hovering
https://eucalyptus.atlassian.net/browse/GUI-1632
> GUI-1632 dash totals now underline when hovering

- eucaconsole/templates/users/user_view.pt
- eucaconsole/views/users.py
hide 'add user to group' button if no groups available
https://eucalyptus.atlassian.net/browse/GUI-1806
> GUI-1806 hide 'add user to group' button if no groups available

- eucaconsole/static/js/pages/image.js
https://eucalyptus.atlassian.net/browse/GUI-1953
> GUI-1953 handle completion of image create on EBS case properly

- eucaconsole/static/js/pages/elb_wizard.js
Fixes https://eucalyptus.atlassian.net/browse/GUI-1955
> GUI-1955: Better threshold for ELB unhealthy-to-healthy instance transition

- eucaconsole/static/js/pages/cloudwatch_charts.js
- eucaconsole/views/cloudwatchapi.py
https://eucalyptus.atlassian.net/browse/GUI-1951
> GUI-1951 added fix for chart loading when session timedout

- conf/console.default.ini
Implements https://eucalyptus.atlassian.net/browse/GUI-1597
> GUI-1597: Bind Pyramid to localhost since nginx is now assumed

- README.rst
- conf/nginx.conf
https://eucalyptus.atlassian.net/browse/GUI-1958
> GUI-1958 Add URL rewrite to nginx configuration, minor README updates.

- eucaconsole/static/css/eucaconsole.css
- eucaconsole/static/css/pages/elb.css
- eucaconsole/static/html/directives/instance_selector.html
- eucaconsole/static/js/widgets/instance_selector.js
- eucaconsole/static/sass/pages/elb.scss
- eucaconsole/views/elbs.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-1957
> GUI-1957: Display reason for unhealthy instance status on ELB Instances page

- eucaconsole/static/css/pages/ipaddresses.css
- eucaconsole/static/sass/pages/ipaddresses.scss
- eucaconsole/templates/ipaddresses/ipaddresses.pt
Set left and right large column widths on form fields and labels.
https://eucalyptus.atlassian.net/browse/GUI-1966
> GUI-1966 Update layout of form fields and labels.

- eucaconsole/static/js/pages/elb_wizard.js
- eucaconsole/templates/elbs/elb_wizard.pt
https://eucalyptus.atlassian.net/browse/GUI-1969
> GUI-1969 Focus name field on page load.

- eucaconsole/tweens.py
- tests/tweens/test_tweens.py
Implements https://eucalyptus.atlassian.net/browse/GUI-1967
> GUI-1967: Tighten CSP by setting form-action directive

- eucaconsole/forms/scalinggroups.py
- eucaconsole/static/js/pages/scalinggroup_policy.js
https://eucalyptus.atlassian.net/browse/GUI-1954
> GUI-1954 - Update form field to text type, special filter on input

- conf/console.default.ini
- eucaconsole/config.py
- eucaconsole/tweens.py
- tests/tweens/test_tweens.py
https://eucalyptus.atlassian.net/browse/GUI-1959
> Gui 1959 log user actions if option configured

- eucaconsole/layout.py
- eucaconsole/static/js/widgets/tag_editor.js
- eucaconsole/templates/panels/tag_editor.pt
disallow tag names starting with 'euca;'
https://eucalyptus.atlassian.net/browse/GUI-1975
> GUI-1975 disallow tag names starting with 'euca:'

- eucaconsole/static/js/pages/scalinggroup.js
https://eucalyptus.atlassian.net/browse/GUI-1979
> GUI-1979 ignore invalid state changes in watch functions, which were setting isNotValid true early

- eucaconsole/templates/instances/instance_create_image.pt
- eucaconsole/templates/instances/instance_view.pt
- eucaconsole/views/instances.py
- eucaconsole/views/panels.py
take bdm from running instance instead of image for createimage from ebs
https://eucalyptus.atlassian.net/browse/GUI-1696
> GUI-1696 take bdm from running instance instead of image for createimage from ebs

- eucaconsole/forms/elbs.py
- eucaconsole/static/js/pages/elb_wizard.js
Bucket name field in Create ELB Wizard requires special validation handling since it is conditionally required.
Fixes https://eucalyptus.atlassian.net/browse/GUI-1986
> GUI-1986: Allow creation of an ELB without access logging enabled

- eucaconsole/tweens.py
source remote_addr from HTTP_X_FORWARDED_FOR where possible in case reverse-proxy is present
https://eucalyptus.atlassian.net/browse/GUI-1959
> GUI-1959 source remote_addr from HTTP_X_FORWARDED_FOR where possible

- eucaconsole/static/html/help/console_user_detail_general.html
Please merge minor revisions into build.
> DOC-1649: misc revisions

- eucaconsole/static/css/pages/instance_create_image.css
- eucaconsole/static/js/jasmine-spec/spec_instance_create_image.js
- eucaconsole/static/js/pages/instance_create_image.js
- eucaconsole/static/js/widgets/create_bucket_dialog.js
- eucaconsole/static/sass/pages/instance_create_image.scss
- eucaconsole/templates/instances/instance_create_image.pt
- eucaconsole/views/elbs.py
- eucaconsole/views/instances.py
- karma.conf.js
Implements https://eucalyptus.atlassian.net/browse/GUI-1721
> GUI-1721: Better handling of S3 bucket creation on "Create image from instance" page

- tests/reqgenerator/reqgenerator.py
an initial load generator that is fully functional for a browsing user
https://eucalyptus.atlassian.net/browse/GUI-1810
> GUI-1810 an initial load generator that is fully functional for a browsing use

- eucaconsole/views/__init__.py
- eucaconsole/views/login.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-1990
> GUI-1990: Opt out of PEP 476 based on config setting

- eucaconsole/static/css/pages/elb_wizard.css
- eucaconsole/static/css/pages/instance_launch.css
- eucaconsole/static/css/pages/launchconfig_wizard.css
- eucaconsole/static/css/pages/scalinggroup_wizard.css
- eucaconsole/static/css/pages/stack_wizard.css
- eucaconsole/static/sass/includes/_wizard.scss
https://eucalyptus.atlassian.net/browse/GUI-1751
> GUI-1751 Specify default cursor for wizard summary.

- eucaconsole/forms/elbs.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-1998
> GUI-1998: Prevent 500 error when updating health checks for an ELB

- eucaconsole/static/css/pages/accounts.css
- eucaconsole/static/css/pages/alarms.css
- eucaconsole/static/css/pages/bucket_contents.css
- eucaconsole/static/css/pages/buckets.css
- eucaconsole/static/css/pages/elb.css
- eucaconsole/static/css/pages/elbs.css
- eucaconsole/static/css/pages/groups.css
- eucaconsole/static/css/pages/images.css
- eucaconsole/static/css/pages/instance.css
- eucaconsole/static/css/pages/instance_types.css
- eucaconsole/static/css/pages/instances.css
- eucaconsole/static/css/pages/ipaddresses.css
- eucaconsole/static/css/pages/keypairs.css
- eucaconsole/static/css/pages/launchconfigs.css
- eucaconsole/static/css/pages/roles.css
- eucaconsole/static/css/pages/scalinggroup.css
- eucaconsole/static/css/pages/scalinggroups.css
- eucaconsole/static/css/pages/securitygroups.css
- eucaconsole/static/css/pages/snapshots.css
- eucaconsole/static/css/pages/stack.css
- eucaconsole/static/css/pages/stacks.css
- eucaconsole/static/css/pages/user.css
- eucaconsole/static/css/pages/users.css
- eucaconsole/static/css/pages/volume.css
- eucaconsole/static/css/pages/volumes.css
- eucaconsole/static/sass/includes/_landingpage.scss
Fixes https://eucalyptus.atlassian.net/browse/GUI-1715
> GUI-1715: Avoid wobble in loading indicator for transitional items on landing pages (tile view)

- eucaconsole/layout.py
- eucaconsole/templates/master_layout.pt
https://eucalyptus.atlassian.net/browse/GUI-2006
> GUI-2006 Update product link to relative path at root.

- eucaconsole/static/js/pages/instance_create_image.js
Fixes https://eucalyptus.atlassian.net/browse/GUI-2010
> GUI-2010: Enable submit button on create image from instance page when an existing bucket is selected.

- eucaconsole/forms/scalinggroups.py
- eucaconsole/static/js/pages/scalinggroup_wizard.js
https://eucalyptus.atlassian.net/browse/GUI-1995
> GUI-1995 Update form field to text type, special filter on input.

- eucaconsole/templates/elbs/elbs.pt
https://eucalyptus.atlassian.net/browse/GUI-1996
> GUI-1996 Make hosts counts links.

- eucaconsole/static/js/widgets/bdmapping_editor.js
- eucaconsole/templates/launchconfigs/launchconfig_view.pt
revert GUI-1945 and fix differently
https://eucalyptus.atlassian.net/browse/GUI-2002
> GUI-2002 fixed bdmapping editor better.

- eucaconsole/constants/elbs.py
- eucaconsole/constants/instances.py
- eucaconsole/static/css/pages/cloudwatch_charts.css
- eucaconsole/static/js/pages/cloudwatch_charts.js
- eucaconsole/static/sass/pages/cloudwatch_charts.scss
- eucaconsole/templates/elbs/elb_monitoring.pt
- eucaconsole/templates/instances/instance_monitoring.pt
- eucaconsole/views/cloudwatchapi.py
- tests/elbs/test_elbs.py
Implements https://eucalyptus.atlassian.net/browse/GUI-1971
> GUI-1971: Improved handling of empty chart messages

- eucaconsole/static/css/eucaconsole.css
- eucaconsole/static/js/widgets/notify.js
- eucaconsole/static/sass/eucaconsole.scss
- eucaconsole/templates/macros.pt
https://eucalyptus.atlassian.net/browse/GUI-1913
> GUI-1913 Update notification styles.

- eucaconsole/templates/instances/instance_launch.pt
- eucaconsole/templates/launchconfigs/launchconfig_wizard.pt
- eucaconsole/templates/panels/bdmapping_editor.pt
- eucaconsole/views/panels.py
https://eucalyptus.atlassian.net/browse/GUI-1708
> GUI-1708 Add missing hr tag.

- eucaconsole/layout.py
- eucaconsole/static/js/thirdparty/magic-search/magic_search.html
- eucaconsole/templates/macros.pt
don't show drop-down if empty
https://eucalyptus.atlassian.net/browse/GUI-1999
> GUI-1999 don't show drop-down if empty

- eucaconsole/static/js/pages/elb_view.js
Fixes https://eucalyptus.atlassian.net/browse/GUI-2022
> GUI-2022: Prevent hidden validation error in bucket name field when ELB listeners are modified and access logs are not enabled

- eucaconsole/templates/dialogs/snapshot_dialogs.pt
https://eucalyptus.atlassian.net/browse/GUI-2004
> GUI-2004 Stack labels, left align checkboxen.

- eucaconsole/forms/elbs.py
- eucaconsole/static/js/pages/elb_wizard.js
- eucaconsole/templates/elbs/elb_wizard.pt
az required, preselects zone, vpc sec group not required
https://eucalyptus.atlassian.net/browse/GUI-2008
> GUI-2008 az required, preselects zone, vpc sec group not required

- eucaconsole/static/css/eucaconsole.css
- eucaconsole/static/sass/eucaconsole.scss
- eucaconsole/templates/panels/bdmapping_editor.pt
https://eucalyptus.atlassian.net/browse/GUI-2023
> GUI-2023 Center table cell value.

- eucaconsole/static/css/eucaconsole.css
- eucaconsole/static/js/widgets/notify.js
- eucaconsole/static/sass/eucaconsole.scss
https://eucalyptus.atlassian.net/browse/GUI-2029
> GUI-2029 Update warning/info notification to new styles.

- eucaconsole/static/css/pages/accounts.css
- eucaconsole/static/css/pages/alarms.css
- eucaconsole/static/css/pages/bucket_contents.css
- eucaconsole/static/css/pages/buckets.css
- eucaconsole/static/css/pages/elb.css
- eucaconsole/static/css/pages/elbs.css
- eucaconsole/static/css/pages/groups.css
- eucaconsole/static/css/pages/images.css
- eucaconsole/static/css/pages/instance.css
- eucaconsole/static/css/pages/instance_types.css
- eucaconsole/static/css/pages/instances.css
- eucaconsole/static/css/pages/ipaddresses.css
- eucaconsole/static/css/pages/keypairs.css
- eucaconsole/static/css/pages/launchconfigs.css
- eucaconsole/static/css/pages/roles.css
- eucaconsole/static/css/pages/scalinggroup.css
- eucaconsole/static/css/pages/scalinggroups.css
- eucaconsole/static/css/pages/securitygroups.css
- eucaconsole/static/css/pages/snapshots.css
- eucaconsole/static/css/pages/stack.css
- eucaconsole/static/css/pages/stacks.css
- eucaconsole/static/css/pages/user.css
- eucaconsole/static/css/pages/users.css
- eucaconsole/static/css/pages/volume.css
- eucaconsole/static/css/pages/volumes.css
- eucaconsole/static/sass/includes/_landingpage.scss
Fixes https://eucalyptus.atlassian.net/browse/GUI-2040
> GUI-2040: Fix typo in CSS border-color rule for split buttons on landing pages

- eucaconsole/constants/__init__.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-2043
> GUI-2043: Ensure user stays on landing page when switching regions in AWS for CloudFormation stacks and load balancers

- eucaconsole/templates/stacks/stack_wizard.pt
removed data-tooltip attr to avoid black box
https://eucalyptus.atlassian.net/browse/GUI-2079
> GUI-2079 removed data-tooltip attr to avoid black box

- eucaconsole/views/stacks.py
filter images on aws to avoid gigantic fetch
https://eucalyptus.atlassian.net/browse/GUI-1918
> GUI-1918, GUI-2095: filter images on aws to avoid gigantic fetch

- eucaconsole/views/stacks.py
set initial value for owner_alias
https://eucalyptus.atlassian.net/browse/GUI-2095
> GUI-2095 set initial value for owner_alias

- eucaconsole/models/auth.py
- eucaconsole/views/buckets.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-2082
> GUI-2082: Prevent unexpected 404 error when viewing object details page on Eucalyptus

- eucaconsole/views/stacks.py
add check before looking in dict
https://eucalyptus.atlassian.net/browse/GUI-2086
> GUI-2086 add check before looking in dict

- eucaconsole/static/css/pages/elb.css
- eucaconsole/static/js/pages/elb_instances.js
- eucaconsole/static/js/widgets/instance_selector.js
- eucaconsole/static/sass/pages/elb.scss
- eucaconsole/templates/elbs/elb_instances.pt
https://eucalyptus.atlassian.net/browse/GUI-2021
> GUI-2021 Add refresh button to ELB Instances page

- eucaconsole/views/scalinggroups.py
- tests/scalinggroups/test_scalinggroups.py
https://eucalyptus.atlassian.net/browse/GUI-2093
> GUI-2093 don't try to modify tags prefixed with aws:, euca: or unmodified

- eucaconsole/views/stacks.py
update stack delete message
https://eucalyptus.atlassian.net/browse/GUI-2089
> GUI-2089 update stack delete message

- eucaconsole/templates/scalinggroups/scalinggroup_view.pt
- eucaconsole/views/scalinggroups.py
- tests/scalinggroups/test_scalinggroups.py
https://eucalyptus.atlassian.net/browse/GUI-1930
> GUI-1930 added the last scaling activity cause into scaling group view

- eucaconsole/static/html/help/console_create_scaling_policy.html
- eucaconsole/static/html/help/console_scaling_group_detail_general.html
- eucaconsole/static/html/help/console_scaling_group_detail_instances.html
- eucaconsole/static/html/help/console_scaling_group_detail_policies.html
Please review minor changes and merge with master.
> DOC-1675: updated help pages per doc ticket.

- eucaconsole/templates/buckets/bucket_upload.pt
https://eucalyptus.atlassian.net/browse/GUI-2118
> GUI-2118 Template cleanup

- eucaconsole/views/stacks.py
fetch amazon and user images for stack form
https://eucalyptus.atlassian.net/browse/GUI-2095
> GUI-2095 fetch amazon and user images for stack form

- eucaconsole/templates/users/user_view.pt
- eucaconsole/views/__init__.py
https://eucalyptus.atlassian.net/browse/GUI-1340
> GUI-1340 check for UnauthorizedOperation error code

- eucaconsole/views/stacks.py
md5 encode stack id to obfuscate it
https://eucalyptus.atlassian.net/browse/GUI-2129
> GUI-2129 md5 encode stack id to obfuscate it

- eucaconsole/config.py
- eucaconsole/static/js/pages/dashboard.js
- eucaconsole/static/js/pages/stacks.js
- eucaconsole/templates/buckets/bucket_item_details.pt
- eucaconsole/templates/dashboard.pt
- eucaconsole/templates/dialogs/ufshost_warn_dialog.pt
- eucaconsole/templates/stacks/stacks.pt
- eucaconsole/utils.py
- eucaconsole/views/buckets.py
- eucaconsole/views/dashboard.py
- eucaconsole/views/dialogs.py
- eucaconsole/views/stacks.py
https://eucalyptus.atlassian.net/browse/GUI-2088
> GUI-2088 Added warnings if ufshost configured for localhost/127.0.0.1

- eucaconsole/views/stacks.py
https://eucalyptus.atlassian.net/browse/GUI-2103
> GUI-2103 fallback to default error handler except in bucket exists case

- eucaconsole/views/stacks.py
added check for cloud_type before checking for aws resources
https://eucalyptus.atlassian.net/browse/GUI-2132
> GUI-2132 added check for cloud_type before checking for aws resources

- eucaconsole/static/js/pages/dashboard.js
- eucaconsole/static/js/pages/stacks.js
- eucaconsole/templates/dialogs/ufshost_warn_dialog.pt
removed additional close button
https://eucalyptus.atlassian.net/browse/GUI-2088
> GUI-2088 removed additional close button

- eucaconsole/views/login.py
- eucaconsole/views/regions.py
https://eucalyptus.atlassian.net/browse/GUI-1978
> GUI-1978 remove VPC capability on AWS if no vpcs defined for account

- eucaconsole/static/js/pages/eucaconsole_utils.js
updated text to determine if 403 is due to permissions
https://eucalyptus.atlassian.net/browse/GUI-2103
> GUI-2103 updated text to determine if 403 is due to permissions

- tests/selenium/guiops/dialogs/bucket_dialogs.py
- tests/selenium/guiops/guiops/guiops.py
- tests/selenium/guiops/guitester/guiec2.py
- tests/selenium/guiops/guitester/guis3.py
- tests/selenium/guiops/guitester/guitester.py
- tests/selenium/guiops/pages/basepage.py
- tests/selenium/guiops/pages/buckets/bucketdetail.py
- tests/selenium/guiops/pages/buckets/buckets_lp.py
- tests/selenium/guiops/pages/dashboard.py
- tests/selenium/guiops/selenium_api/selenium_api.py
- tests/selenium/guiops/tests/buckets.py
- tests/selenium/guiops/tests/keypair.py
https://eucalyptus.atlassian.net/browse/GUI-2114
> GUI-2114 Bucket Automated Tests

- eucaconsole/forms/accounts.py
https://eucalyptus.atlassian.net/browse/GUI-2146
> GUI-2146 Remove validators to solve seemingly unrelated problem.

- eucaconsole/static/js/pages/elb_view.js
- eucaconsole/static/js/pages/elb_wizard.js
Cross-browser fix for https://eucalyptus.atlassian.net/browse/GUI-2160
> GUI-2160: Minor fix to prevent security group rules warning dialog from displaying on non-VPC clouds in Firefox and Chrome

- eucaconsole/static/html/help/console_create_load_balancer_health.html
- eucaconsole/static/html/help/console_load_balancer_detail_general.html
@kamalgill : please review and merge if changes are acceptable. Thanks!!!
> DOC-1692: updated help to reflect workaround for prefix path error bugs.

- eucaconsole/views/instances.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-2148
> GUI-2148: Better handling of empty user data to avoid decoding error

- eucaconsole/constants/elbs.py
- eucaconsole/forms/elbs.py
- eucaconsole/templates/elbs/elb_view.pt
- eucaconsole/templates/elbs/elb_wizard.pt
- eucaconsole/views/elbs.py
Fixes:
- https://eucalyptus.atlassian.net/browse/GUI-2173
- https://eucalyptus.atlassian.net/browse/GUI-2174
> GUI-2173, GUI-2174: Allow empty ELB access logs prefix; add validation to keep prefix lowercase

- eucaconsole/static/js/widgets/elb_listener_editor.js
- eucaconsole/views/elbs.py
handle different protocols for each side of listener
https://eucalyptus.atlassian.net/browse/GUI-2175
> GUI-2175 handle different protocols for each side of listener

- eucaconsole/forms/buckets.py
- eucaconsole/templates/dialogs/create_bucket_dialog.pt
Fixes https://eucalyptus.atlassian.net/browse/GUI-2162
> GUI-2162: Prevent uppercase letters in bucket name when creating a bucket for storing ELB access logs

- eucaconsole/templates/buckets/bucket_contents.pt
Fixes https://eucalyptus.atlassian.net/browse/GUI-1926
> GUI-1926: Disable file upload button on bucket contents page when file uploads are disabled in console.ini

- eucaconsole/views/stacks.py
log warning if cf samples bucket isn't configured properly
https://eucalyptus.atlassian.net/browse/GUI-1754
> Gui 1754 log warning if cf samples bucket isn't configured properly

- eucaconsole/templates/instances/instance_create_image.pt
removed maxlength setting from password input field
https://eucalyptus.atlassian.net/browse/GUI-1695
> Gui 1695 removed maxlength setting from password input field

- eucaconsole/views/buckets.py
modify xhr view connection to stop suppressing consec slashes
https://eucalyptus.atlassian.net/browse/GUI-1993
> Gui 1993 modify xhr view connection to stop suppressing consec slashes

- eucaconsole/forms/instances.py
- eucaconsole/forms/launchconfigs.py
- eucaconsole/static/js/pages/instance_launch_more.js
- eucaconsole/static/js/pages/instances.js
- eucaconsole/static/js/pages/launchconfig_wizard.js
- eucaconsole/templates/instances/instance_launch_more.pt
- eucaconsole/templates/launchconfigs/launchconfig_wizard.pt
- eucaconsole/views/launchconfigs.py
https://eucalyptus.atlassian.net/browse/GUI-2154
> Gui 2154 populate user data for "launch config like" and "launch more"

- eucaconsole/constants/instances.py
- tests/instances/test_instances.py
https://eucalyptus.atlassian.net/browse/GUI-1843
> Gui 1843 fix typo in instance type

- eucaconsole/static/js/widgets/securitygroup_rules.js
- eucaconsole/templates/panels/securitygroup_rules.pt
- eucaconsole/views/panels.py
- eucaconsole/views/securitygroups.py
https://eucalyptus.atlassian.net/browse/GUI-1923
> Gui 1923 include internal elb groups in sec group rules editor

- conf/console.default.ini
default to false for password.save
https://eucalyptus.atlassian.net/browse/GUI-2117
> GUI-2117 default to false for password.save

- eucaconsole/static/css/pages/buckets.css
- eucaconsole/static/sass/pages/buckets.scss
Fixes https://eucalyptus.atlassian.net/browse/GUI-2177
> GUI-2177: Bump down bucket icon size in tile view on buckets landing page

- eucaconsole/views/volumes.py
https://eucalyptus.atlassian.net/browse/GUI-1925
> Gui 1925 don't filter snapshot request when volumes exceed 1000

- eucaconsole/static/js/pages/elb_wizard.js
Fixes https://eucalyptus.atlassian.net/browse/GUI-2159
> GUI-2159: Disable "Create Load Balancer" button in ELB wizard when access logging is enabled and a bucket isn't selected or created

- conf/nginx.conf
- eucaconsole/templates/master_layout.pt
https://eucalyptus.atlassian.net/browse/GUI-2171
> GUI-2171 X-UA-Compatible for IE

- eucaconsole/static/sass/eucaconsole.scss
https://eucalyptus.atlassian.net/browse/GUI-2137
> GUI-2137 Notification Text.

- eucaconsole/templates/stacks/stack_wizard.pt
- tests/selenium/guiops/pages/stacks/create_stack.py
- tests/selenium/guiops/selenium_api/selenium_api.py
got stack create working... mostly by fixing duplicate button ID
https://eucalyptus.atlassian.net/browse/GUI-2108
> GUI-2108 got stack create working... mostly by fixing duplicate button ID

- eucaconsole/static/js/pages/elb_wizard.js
Fixes https://eucalyptus.atlassian.net/browse/GUI-2041
> GUI-2041: Set ELB health check protocol/port from first instance protocol/port entry in listeners list

- README.rst
Documents workarounds for https://eucalyptus.atlassian.net/browse/GUI-2209
> GUI-2209: Document workarounds for source install issues on recent versions of OS X

- eucaconsole/forms/accounts.py
- eucaconsole/static/css/eucaconsole.css
- eucaconsole/templates/accounts/account_new.pt
- eucaconsole/templates/panels/user_editor.pt
- eucaconsole/views/accounts.py
https://eucalyptus.atlassian.net/browse/GUI-2190
> GUI-2190 Account User Credentials Creation Options

- eucaconsole/templates/images/image_view.pt
- eucaconsole/views/images.py
https://eucalyptus.atlassian.net/browse/GUI-2164
> Gui 2164 pass progress from task to image, fix progress bar look

- eucaconsole/static/html/help/console_create_iam_accounts.html
- eucaconsole/static/html/help/console_create_iam_users.html
DOC-1704: Please merge these approved changes for 4.2.1. Thanks!
> DOC-1704: final changes per JLO review inputs for 4.2.1 updates.

- eucaconsole/static/js/widgets/bdmapping_editor.js
https://eucalyptus.atlassian.net/browse/GUI-2225
> GUI-2225 guard against error when bdMapping is not present.

- tests/selenium/guiops/pages/volume/volume_view.py
- tests/selenium/guiops/tests/volumes.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-2323
> GUI-2323: Fix volumes sequence, which failed on the volume status selector due to introducing expandos

- eucaconsole/static/html/directives/instance_selector.html
- eucaconsole/templates/instances/instances.pt
fixed references to instance placement
https://eucalyptus.atlassian.net/browse/GUI-2324
> GUI-2324 fixed references to instance placement

- eucaconsole/templates/dashboard.pt
changed state param to status
https://eucalyptus.atlassian.net/browse/GUI-2326
> GUI-2326 changed state param to status

- eucaconsole/static/js/pages/landingpage.js
- eucaconsole/static/js/widgets/image_picker.js
converted to client-side filtering, except for aws
https://eucalyptus.atlassian.net/browse/GUI-2252
> GUI-2252 converted to client-side filtering, except for aws

- conf/memcached
updated memcached config for unix domain socket
https://eucalyptus.atlassian.net/browse/GUI-2341
> GUI-2341 updated memcached config for unix domain socket

- .travis.yml
- eucaconsole/static/css/widgets/tag-editor.css
- eucaconsole/static/js/jasmine-spec/tag-editor/spec_tag_editor.js
- eucaconsole/static/js/pages/elb_view.js
- eucaconsole/static/js/widgets/tag-editor/tag-editor.js
- eucaconsole/static/sass/widgets/tag-editor.scss
- eucaconsole/templates/elbs/elb_view.pt
- eucaconsole/templates/tag-editor/tag-editor.pt
- eucaconsole/views/__init__.py
- eucaconsole/views/elbs.py
- setup.py
- tests/elbs/test_elbs.py
https://eucalyptus.atlassian.net/browse/GUI-2277
> GUI-2277 Integrate tag-editor into ELB View

- .travis.yml
- eucaconsole/views/stacks.py
- setup.py
- tests/elbs/test_elbs.py
- tests/selenium/guiops/tests/buckets.py
https://eucalyptus.atlassian.net/browse/GUI-2246
> GUI-2246 don't parse/dump template text when viewing template

- eucaconsole/static/js/pages/image.js
- eucaconsole/templates/images/image_view.pt
- eucaconsole/views/images.py
https://eucalyptus.atlassian.net/browse/GUI-2279
> GUI-2279 - Integrate tag-editor into Image Detail page.

- eucaconsole/views/stacks.py
prevent stack_view from error-ing if cf-templates bucket doesn't exist
https://eucalyptus.atlassian.net/browse/GUI-2223
> GUI-2223 prevent stack_view from error-ing if cf-templates bucket doesn't exist

- eucaconsole/views/launchconfigs.py
handle case where image deleted
https://eucalyptus.atlassian.net/browse/GUI-2346
> GUI-2346 handle case where image deleted

- tests/selenium/guiops/pages/security_group/security_group_detail.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-2352
> GUI-2352: Fix security groups sequence

- eucaconsole/templates/instances/instance_view.pt
https://eucalyptus.atlassian.net/browse/GUI-2334
> Gui 2334 removed errant conditional display of instance type

- eucaconsole/static/js/widgets/tag-editor/tag-editor.js
https://eucalyptus.atlassian.net/browse/GUI-2349
> GUI-2349 Filter out cloud formation tags beginning w/ aws: or euca:

- eucaconsole/static/css/pages/accounts.css
- eucaconsole/static/css/pages/alarms.css
- eucaconsole/static/css/pages/bucket_contents.css
- eucaconsole/static/css/pages/buckets.css
- eucaconsole/static/css/pages/elb.css
- eucaconsole/static/css/pages/elbs.css
- eucaconsole/static/css/pages/groups.css
- eucaconsole/static/css/pages/images.css
- eucaconsole/static/css/pages/instance.css
- eucaconsole/static/css/pages/instance_types.css
- eucaconsole/static/css/pages/instances.css
- eucaconsole/static/css/pages/ipaddresses.css
- eucaconsole/static/css/pages/keypairs.css
- eucaconsole/static/css/pages/launchconfigs.css
- eucaconsole/static/css/pages/roles.css
- eucaconsole/static/css/pages/scalinggroup.css
- eucaconsole/static/css/pages/scalinggroups.css
- eucaconsole/static/css/pages/securitygroups.css
- eucaconsole/static/css/pages/snapshots.css
- eucaconsole/static/css/pages/stack.css
- eucaconsole/static/css/pages/stacks.css
- eucaconsole/static/css/pages/user.css
- eucaconsole/static/css/pages/users.css
- eucaconsole/static/css/pages/volume.css
- eucaconsole/static/css/pages/volumes.css
- eucaconsole/static/sass/includes/_landingpage.scss
Fixes https://eucalyptus.atlassian.net/browse/GUI-2239
> GUI-2239: Avoid wobble in loading indicator for transitional items on landing pages (table view)

- eucaconsole/static/js/pages/elb_view.js
Fixes https://eucalyptus.atlassian.net/browse/GUI-2250
> GUI-2250: Display warning modal when clicking Save Changes button on ELB detail page during an incomplete attempt to add a listener

- conf/console.default.ini
- conf/memcached
set memcached to work with domain socket
https://eucalyptus.atlassian.net/browse/GUI-1782
> GUI-1782 set memcached to work with domain socket

- eucaconsole/templates/panels/image_picker.pt
- tests/selenium/guiops/guitester/guiasg.py
- tests/selenium/guiops/pages/autoscaling/asg_detail.py
- tests/selenium/guiops/pages/autoscaling/create_asg.py
- tests/selenium/guiops/pages/autoscaling/create_launch_config.py
- tests/selenium/guiops/pages/volume/volume_detail.py
- tests/selenium/guiops/tests/autoscaling.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-2380
> GUI-2380: Fix Auto Scaling functional test sequence

- eucaconsole/views/__init__.py
added host into cache key when invalidating cache
https://eucalyptus.atlassian.net/browse/GUI-2383
> GUI-2383 added host into cache key when invalidating cache

- eucaconsole/views/login.py
- eucaconsole/views/stacks.py
added support for new stack param types, fixed default region bug that blocked testing this
https://eucalyptus.atlassian.net/browse/GUI-2336
> GUI-2336 added support for new stack param types

- eucaconsole/static/js/pages/ipaddress.js
added search_contains option to chosen on ip addr detail page
https://eucalyptus.atlassian.net/browse/GUI-2384
> GUI-2384 added search_contains option to chosen on ip addr detail page

- eucaconsole/static/js/pages/instances.js
- eucaconsole/views/instances.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-2413
> GUI-2413: Avoid fetching instance profiles/roles for instances landing page on AWS

- eucaconsole/config.py
https://eucalyptus.atlassian.net/browse/GUI-2377
> GUI-2377: Restrict Pyramid's config.scan() to eucaconsole.views package

- eucaconsole/constants/scalinggroups.py
- eucaconsole/static/js/pages/cloudwatch_charts.js
- eucaconsole/templates/scalinggroups/scalinggroup_monitoring.pt
- eucaconsole/views/scalinggroups.py
- tests/selenium/guiops/guitester/guiasg.py
- tests/selenium/guiops/pages/autoscaling/asg_detail.py
- tests/selenium/guiops/tests/autoscaling.py
Implements https://eucalyptus.atlassian.net/browse/GUI-2368
> GUI-2368: Charts for instance metrics on auto scaling group details page

- tests/selenium/guiops/guitester/guiasg.py
- tests/selenium/guiops/guitester/guiec2.py
- tests/selenium/guiops/guitester/guitester.py
- tests/selenium/guiops/pages/autoscaling/asg_detail.py
- tests/selenium/guiops/pages/basepage.py
- tests/selenium/guiops/pages/volume/volume_view.py
- tests/selenium/guiops/selenium_api/selenium_api.py
- tests/selenium/guiops/tests/instances.py
- tests/selenium/guiops/tests/run_all_sequences.py
https://eucalyptus.atlassian.net/browse/GUI-2422
https://eucalyptus.atlassian.net/browse/GUI-2431
> Temporary fix to instances sequence

- tests/selenium/guiops/dialogs/volume_dialogs.py
- tests/selenium/guiops/guitester/guiec2.py
- tests/selenium/guiops/pages/instance/instancedetail.py
- tests/selenium/guiops/pages/volume/volume_detail.py
- tests/selenium/guiops/selenium_api/selenium_api.py
https://eucalyptus.atlassian.net/browse/GUI-2437
> Fix to attach volume failing silently

- tests/selenium/guiops/dialogs/keypair_dialogs.py
- tests/selenium/guiops/dialogs/security_group_dialogs.py
- tests/selenium/guiops/dialogs/volume_dialogs.py
- tests/selenium/guiops/guiops/guiops.py
- tests/selenium/guiops/guitester/guiec2.py
- tests/selenium/guiops/pages/basepage.py
- tests/selenium/guiops/pages/dashboard.py
- tests/selenium/guiops/pages/instance/instance_lp.py
- tests/selenium/guiops/pages/instance/instancedetail.py
- tests/selenium/guiops/pages/keypair/keypair_lp.py
- tests/selenium/guiops/pages/keypair/keypairdetail.py
- tests/selenium/guiops/pages/loginpage.py
- tests/selenium/guiops/pages/security_group/security_group_detail.py
- tests/selenium/guiops/pages/security_group/security_group_lp.py
- tests/selenium/guiops/pages/volume/volume_detail.py
- tests/selenium/guiops/pages/volume/volume_view.py
- tests/selenium/guiops/tests/instances.py
- tests/selenium/guiops/tests/option_parser.py
- tests/selenium/guiops/tests/security_groups.py
- tests/selenium/guiops/tests/volumes.py
WIP test for https://eucalyptus.atlassian.net/browse/GUI-2430
To be confirmed via a Jenkins run before full implementation/refactoring.
> GUI-2430: Allow availability zones to be passed as a command-line arg for the volumes sequence

- eucaconsole/templates/macros.pt
- eucaconsole/templates/volumes/volumes.pt
- tests/selenium/guiops/dialogs/instance_dialogs.py
- tests/selenium/guiops/guitester/guiec2.py
- tests/selenium/guiops/pages/autoscaling/create_launch_config.py
- tests/selenium/guiops/pages/volume/volume_view.py
- tests/selenium/guiops/selenium_api/selenium_api.py
https://eucalyptus.atlassian.net/browse/GUI-2433
> GUI-2433 disabled expando for volumes landing

- eucaconsole/constants/cloudwatch.py
- eucaconsole/forms/alarms.py
- eucaconsole/models/quotas.py
- eucaconsole/views/users.py
merging last 4.2.2 fixes to master
> feb22-maint42-master

- eucaconsole/static/html/help/console_create_instances_advanced.html
- eucaconsole/static/html/help/console_create_launch_config_advanced.html
No hooks needed, this ticket is a revision to a existing topics.
> DOC-1791: updated topics to include missing parameter.

- eucaconsole/static/html/help/console_create_alarm.html
- eucaconsole/static/html/help/console_instance_detail.html
- eucaconsole/static/html/help/console_scaling_group_detail_general.html
- eucaconsole/static/html/help/console_scaling_group_detail_policies.html
- eucaconsole/static/html/help/console_stack_detail_events.html
No new hooks needed; revisions to existing content only.
> DOC-1797: various revisions to improve output, see ticket for details.

- eucaconsole/static/js/pages/securitygroups.js
- eucaconsole/templates/dialogs/securitygroup_dialogs.pt
- eucaconsole/templates/securitygroups/securitygroups.pt
- eucaconsole/views/securitygroups.py
Implements https://eucalyptus.atlassian.net/browse/GUI-2307
> GUI-2307: Enable multi-select actions on security groups landing page

- eucaconsole/static/js/pages/keypairs.js
- eucaconsole/templates/dialogs/keypair_dialogs.pt
- eucaconsole/templates/keypairs/keypairs.pt
- eucaconsole/views/keypairs.py
Implements https://eucalyptus.atlassian.net/browse/GUI-2313
> GUI-2313: Enable multi-select actions on key pairs landing page

- eucaconsole/static/js/pages/landingpage.js
Fixes https://eucalyptus.atlassian.net/browse/GUI-2446
> GUI-2446: Avoid wiping out selected items and automatically closing More Actions menu during smart refresh

- eucaconsole/static/js/pages/snapshots.js
- eucaconsole/templates/snapshots/snapshots.pt
- eucaconsole/views/snapshots.py
Implements https://eucalyptus.atlassian.net/browse/GUI-2292
> GUI-2292:  Implement sortable tables on snapshots landing page

- eucaconsole/static/js/pages/keypairs.js
- eucaconsole/static/js/pages/securitygroups.js
- eucaconsole/templates/keypairs/keypairs.pt
- eucaconsole/templates/securitygroups/securitygroups.pt
- eucaconsole/views/keypairs.py
- eucaconsole/views/securitygroups.py
Implements:
- https://eucalyptus.atlassian.net/browse/GUI-2297
- https://eucalyptus.atlassian.net/browse/GUI-2298
> GUI-2297, GUI-2298: Implement sortable tables on security groups and key pairs landing pages

- eucaconsole/static/js/pages/images.js
- eucaconsole/templates/images/images.pt
- eucaconsole/views/images.py
Implements https://eucalyptus.atlassian.net/browse/GUI-2296
> GUI-2296: Implement sortable tables for images landing page

- eucaconsole/static/js/pages/instances.js
- eucaconsole/templates/instances/instances.pt
- eucaconsole/views/instances.py
- tests/instances/test_instances.py
Implements https://eucalyptus.atlassian.net/browse/GUI-2333
> GUI-2333: Implement sortable tables on instances landing page

- eucaconsole/models/alarms.py
- tests/alarms/test_alarms.py
… useful for https://eucalyptus.atlassian.net/browse/GUI-2464 and elsewhere
> Implement reusable method for fetching alarms for a given resource

- eucaconsole/static/css/pages/instances.css
- eucaconsole/static/sass/pages/instances.scss
- eucaconsole/templates/instances/instances.pt
...and set default sorting to most recently launched instances
Fixes https://eucalyptus.atlassian.net/browse/GUI-2476
> GUI-2476: Display launch time info on instances landing page... 

- eucaconsole/static/css/eucaconsole.css
- eucaconsole/static/css/pages/alarm-state-view.css
- eucaconsole/static/js/pages/alarm_state_view.js
- eucaconsole/static/sass/pages/alarm-state-view.scss
- eucaconsole/templates/cloudwatch/alarm_state_view.pt
https://eucalyptus.atlassian.net/browse/GUI-2468
> GUI 2468 fixed ux concerns

- eucaconsole/static/js/pages/alarm_state_view.js
- eucaconsole/static/js/pages/instance_monitoring.js
- eucaconsole/static/js/pages/resource_monitoring.js
- eucaconsole/templates/cloudwatch/alarm_state_view.pt
- eucaconsole/templates/instances/instance_monitoring.pt
- eucaconsole/templates/scalinggroups/scalinggroup_monitoring.pt
https://eucalyptus.atlassian.net/browse/GUI-2469
> GUI-2469 implemented alarm view/delete for scaling group monitoring page

- eucaconsole/static/js/pages/alarm_state_view.js
- eucaconsole/static/js/pages/instance_monitoring.js
- eucaconsole/static/js/pages/resource_monitoring.js
- eucaconsole/templates/cloudwatch/alarm_state_view.pt
- eucaconsole/templates/instances/instance_monitoring.pt
- eucaconsole/templates/scalinggroups/scalinggroup_monitoring.pt
- eucaconsole/templates/volumes/volume_monitoring.pt
https://eucalyptus.atlassian.net/browse/GUI-2470
This should be merged AFTER PR#1840
> Gui 2470 alarm view/delete for volumes

- eucaconsole/static/js/pages/alarm_state_view.js
- eucaconsole/static/js/pages/instance_monitoring.js
- eucaconsole/static/js/pages/resource_monitoring.js
- eucaconsole/templates/cloudwatch/alarm_state_view.pt
- eucaconsole/templates/elbs/elb_monitoring.pt
- eucaconsole/templates/instances/instance_monitoring.pt
- eucaconsole/templates/scalinggroups/scalinggroup_monitoring.pt
https://eucalyptus.atlassian.net/browse/GUI-2471
This should be merged AFTER PR#1840
> Gui 2471 alarm view/delete for load balancers

- eucaconsole/static/css/pages/scalinggroups.css
- eucaconsole/static/sass/pages/scalinggroups.scss
- eucaconsole/templates/scalinggroups/scalinggroups.pt
- eucaconsole/views/scalinggroups.py
Implements https://eucalyptus.atlassian.net/browse/GUI-2462
Note: This branch was cut from GUI-2463, so https://github.com/eucalyptus/eucaconsole/pull/1841 should be merged prior to this one
> GUI-2462: Display alarm status on scaling groups landing page

- eucaconsole/static/css/pages/volumes.css
- eucaconsole/static/sass/pages/volumes.scss
- eucaconsole/templates/volumes/volumes.pt
- eucaconsole/views/volumes.py
- tests/volumes/test_volumes.py
Implements https://eucalyptus.atlassian.net/browse/GUI-2465
Note: This branch was cut from GUI-2463, so #1841 should be merged prior to this one
> GUI-2465: Display alarm status on volumes landing page  

- eucaconsole/layout.py
- eucaconsole/views/__init__.py
- eucaconsole/views/elbs.py
- eucaconsole/views/instances.py
- eucaconsole/views/ipaddresses.py
- eucaconsole/views/securitygroups.py
https://eucalyptus.atlassian.net/browse/GUI-2417
> GUI-2417 improved error handling in case where UFS is unreachable

- eucaconsole/static/css/pages/alarm-state-view.css
- eucaconsole/static/sass/pages/alarm-state-view.scss
- eucaconsole/templates/cloudwatch/alarm_state_view.pt
https://eucalyptus.atlassian.net/browse/GUI-2479
> GUI-2479 set alarm summary to use directive for state

- eucaconsole/models/auth.py
Proper fix for https://eucalyptus.atlassian.net/browse/GUI-2497
> GUI-2497: Consolidate ssl context patch and handle missing 'context' kwarg for httplib.HTTPSConnection in Python < 2.7.9

- eucaconsole/views/__init__.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-2490 for 4.2.2
> GUI-2490: Avoid caching file download responses

- eucaconsole/views/__init__.py
https://eucalyptus.atlassian.net/browse/GUI-2488
> GUI-2488 add csrf token checking for file download

- eucaconsole/templates/instances/instance_view.pt
https://eucalyptus.atlassian.net/browse/GUI-2154
> GUI-2154 ensure user data included when creating launch config from instance

- eucaconsole/static/css/widgets/modal.css
- eucaconsole/static/js/widgets/modal.js
- eucaconsole/static/sass/widgets/modal.scss
based on work done in GUI-2407
> angular-friendly modal

- eucaconsole/templates/instances/instance_view.pt
- eucaconsole/views/__init__.py
> Mar29 maint 4.2 master

- eucaconsole/layout.py
- tests/selenium/guiops/pages/snapshot/create_snapshot.py
https://eucalyptus.atlassian.net/browse/GUI-2498
> GUI-2498 additional check for undefined default region

- eucaconsole/views/stacks.py
https://eucalyptus.atlassian.net/browse/GUI-2510
> GUI-2510 added missing commas in resources list

- eucaconsole/constants/cloudwatch.py
- eucaconsole/static/css/pages/volume_monitoring.css
- eucaconsole/static/sass/pages/volume_monitoring.scss
- eucaconsole/templates/volumes/volume_monitoring.pt
- eucaconsole/views/metrics.py
Implements https://eucalyptus.atlassian.net/browse/GUI-2408
> GUI-2408: Create alarms from volume details page monitoring tab

- eucaconsole/views/metrics.py
https://eucalyptus.atlassian.net/browse/GUI-2516
> GUI-2516 converted volumes call to use filters

- eucaconsole/constants/__init__.py
- eucaconsole/static/css/pages/metrics.css
- eucaconsole/static/js/pages/metrics.js
- eucaconsole/static/js/widgets/create-alarm-modal/create-alarm.js
- eucaconsole/static/sass/pages/metrics.scss
- eucaconsole/templates/cloudwatch/create_alarm_modal_template.pt
- eucaconsole/templates/cloudwatch/metrics.pt
- eucaconsole/views/alarms.py
https://eucalyptus.atlassian.net/browse/GUI-2466
> Gui 2466 create alarm from metrics landing.

- eucaconsole/templates/cloudwatch/create_alarm_dialog.pt
- eucaconsole/templates/elbs/elb_monitoring.pt
- eucaconsole/templates/instances/instance_monitoring.pt
- eucaconsole/templates/volumes/volume_monitoring.pt
- eucaconsole/views/panels.py
Implements the following for https://eucalyptus.atlassian.net/browse/GUI-2504 ...
- Bump up create alarm modal size to xlarge on instance and volume monitoring pages
- Remove unused create alarm dialog panel/template code
> GUI-2504: Minor layout fixes for Create Alarm dialog

- eucaconsole/models/alarms.py
- eucaconsole/routes.py
- eucaconsole/static/css/pages/alarm-detail.css
- eucaconsole/static/css/pages/elb_monitoring.css
- eucaconsole/static/css/pages/instance_monitoring.css
- eucaconsole/static/css/pages/metrics.css
- eucaconsole/static/css/pages/volume_monitoring.css
- eucaconsole/static/css/widgets/alarm-actions.css
- eucaconsole/static/js/pages/metrics.js
- eucaconsole/static/js/services/alarm-service.js
- eucaconsole/static/js/widgets/create-alarm-modal/create-alarm.js
- eucaconsole/static/js/widgets/modal.js
- eucaconsole/static/sass/pages/metrics.scss
- eucaconsole/static/sass/widgets/alarm-actions.scss
- eucaconsole/templates/cloudwatch/create_alarm_modal_template.pt
- eucaconsole/templates/cloudwatch/metrics.pt
- eucaconsole/views/alarms.py
https://eucalyptus.atlassian.net/browse/GUI-2466
> Gui 2466 several fixes.

- eucaconsole/static/css/eucaconsole.css
- eucaconsole/static/css/pages/alarm-detail.css
- eucaconsole/static/css/pages/elb_monitoring.css
- eucaconsole/static/css/pages/instance_monitoring.css
- eucaconsole/static/css/pages/volume_monitoring.css
- eucaconsole/static/css/widgets/alarm-actions.css
- eucaconsole/static/js/pages/alarms/alarm_detail.js
- eucaconsole/static/js/services/metric-service.js
- eucaconsole/static/sass/eucaconsole.scss
- eucaconsole/static/sass/pages/alarm-detail.scss
- eucaconsole/static/sass/widgets/alarm-actions.scss
- eucaconsole/templates/cloudwatch/alarm_actions.pt
- eucaconsole/templates/cloudwatch/alarms_detail.pt
- eucaconsole/templates/cloudwatch/create_alarm_modal_template.pt
https://eucalyptus.atlassian.net/browse/GUI-2457
> GUI-2457, update form validation on alarm detail page.

- eucaconsole/views/elbs.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-2536
> GUI-2536: Better handling of ELB subnet/zone registration

- eucaconsole/templates/cloudwatch/alarms.pt
https://eucalyptus.atlassian.net/browse/GUI-2522
> GUI-2522, fill template slot with base64 encoded url.

- eucaconsole/templates/instances/instance_monitoring.pt
- eucaconsole/templates/volumes/volume_monitoring.pt
https://eucalyptus.atlassian.net/browse/GUI-2519
> GUI-2519 ensured consistency in wording

- eucaconsole/views/metrics.py
small tweak for custom graphs
eucaconsole/views/metrics.py
> GUI-1892 small tweak for custom graphs

- eucaconsole/static/css/pages/alarm-state-view.css
- eucaconsole/static/js/pages/alarm_state_view.js
- eucaconsole/static/sass/pages/alarm-state-view.scss
- eucaconsole/templates/cloudwatch/alarm_state_view.pt
- eucaconsole/templates/dialogs/delete_alarm_dialog.pt
https://eucalyptus.atlassian.net/browse/GUI-2538
> GUI-2538 modified alarm-state-view to reflect delete (not remove) alarm

- eucaconsole/static/css/pages/alarm_history.css
- eucaconsole/static/js/pages/alarms/alarm_history.js
- eucaconsole/static/sass/pages/alarm_history.scss
- eucaconsole/templates/cloudwatch/alarms_history.pt
- eucaconsole/views/alarms.py
https://eucalyptus.atlassian.net/browse/GUI-2472
> GUI-2472, display alarm details modal, copy, download

- eucaconsole/static/css/eucaconsole.css
- eucaconsole/static/css/pages/alarm-detail.css
- eucaconsole/static/css/pages/alarm-state-view.css
- eucaconsole/static/css/pages/alarms.css
- eucaconsole/static/js/pages/alarms/alarm_detail.js
- eucaconsole/static/sass/eucaconsole.scss
- eucaconsole/static/sass/includes/_eucavariables.scss
- eucaconsole/static/sass/pages/alarm-detail.scss
- eucaconsole/static/sass/pages/alarm-state-view.scss
- eucaconsole/static/sass/pages/alarms.scss
- eucaconsole/static/sass/widgets/_delete_alarm_dialog.scss
- eucaconsole/templates/cloudwatch/alarm_state_view.pt
- eucaconsole/templates/cloudwatch/alarms_detail.pt
- eucaconsole/templates/dialogs/delete_alarm_dialog.pt
- eucaconsole/views/dialogs.py
Includes fix for chrome bold/strong tag rendering issue (GUI-2521)
Fixes:
- https://eucalyptus.atlassian.net/browse/GUI-2548
- https://eucalyptus.atlassian.net/browse/GUI-2521
> GUI-2548, GUI-2521: Reuse delete alarm confirmation dialog on alarm details page

- eucaconsole/static/js/pages/cloudwatch_charts.js
https://eucalyptus.atlassian.net/browse/GUI-2517
> GUI-2517 ensure charts don't fetch data if not provided with proper data

- eucaconsole/static/js/pages/alarms/alarm_detail.js
- eucaconsole/templates/cloudwatch/alarms_detail.pt
- eucaconsole/views/alarms.py
Minor follow-up fix for https://eucalyptus.atlassian.net/browse/GUI-2523 , which was mostly fixed in #1900
> GUI-2523: Handle when resource in dimensions is no longer available

- eucaconsole/static/js/widgets/create-alarm-modal/create-alarm.js
- eucaconsole/templates/cloudwatch/create_alarm_modal_template.pt
Minor tweaks for https://eucalyptus.atlassian.net/browse/GUI-2199
> GUI-2199: Better handling of alarm name in Copy Alarm dialog

- eucaconsole/static/js/pages/elb_wizard.js
- eucaconsole/static/js/widgets/instance_selector.js
Fixes https://eucalyptus.atlassian.net/browse/GUI-2564
> GUI-2564: Ensure proper instance count is reflected per zone on ELB Instances page

- eucaconsole/views/metrics.py
https://eucalyptus.atlassian.net/browse/GUI-2571
> GUI-2571 allow custom metrics w/o dimensions

- eucaconsole/static/css/pages/scalinggroup.css
- eucaconsole/static/js/pages/scalinggroup_policies.js
- eucaconsole/static/sass/pages/scalinggroup.scss
- eucaconsole/templates/scalinggroups/scalinggroup_policies.pt
- eucaconsole/templates/scalinggroups/scalinggroup_policy.pt
- eucaconsole/views/scalinggroups.py
Implements https://eucalyptus.atlassian.net/browse/GUI-2543
> GUI-2543: Rework scaling policies page to better handle multi-alarm policies

- eucaconsole/static/js/pages/instance_launch.js
- eucaconsole/static/js/pages/launchconfig_wizard.js
- eucaconsole/views/keypairs.py
https://eucalyptus.atlassian.net/browse/GUI-2489
> GUI-2489 stop passing key material back and forth across the wire

- eucaconsole/templates/cloudwatch/metrics.pt
- eucaconsole/views/metrics.py
https://eucalyptus.atlassian.net/browse/GUI-2561
https://eucalyptus.atlassian.net/browse/GUI-2560
> Gui 2561 fixed namespace, duplicate js import and unique_name

- eucaconsole/static/css/eucaconsole.css
- eucaconsole/static/css/pages/metrics.css
- eucaconsole/static/sass/pages/metrics.scss
- eucaconsole/templates/cloudwatch/metrics.pt
https://eucalyptus.atlassian.net/browse/GUI-2503
> GUI-2503 updated split view grab handle

- eucaconsole/static/css/pages/alarm-detail.css
- eucaconsole/static/css/pages/alarms.css
- eucaconsole/static/css/pages/elb_monitoring.css
- eucaconsole/static/css/pages/elbs.css
- eucaconsole/static/css/pages/instance_monitoring.css
- eucaconsole/static/css/pages/instances.css
- eucaconsole/static/css/pages/metrics.css
- eucaconsole/static/css/pages/scalinggroup_monitoring.css
- eucaconsole/static/css/pages/scalinggroup_policy.css
- eucaconsole/static/css/pages/scalinggroups.css
- eucaconsole/static/css/pages/volume_monitoring.css
- eucaconsole/static/css/pages/volumes.css
- eucaconsole/static/css/widgets/create-alarm-dialog.css
- eucaconsole/static/js/pages/alarms/alarms_landing.js
- eucaconsole/static/js/pages/custom_filters.js
- eucaconsole/static/js/widgets/create-alarm-modal/create-alarm.js
- eucaconsole/static/sass/includes/_landingpage.scss
- eucaconsole/static/sass/pages/alarms.scss
- eucaconsole/static/sass/widgets/create-alarm-dialog.scss
- eucaconsole/templates/cloudwatch/alarms.pt
- eucaconsole/templates/cloudwatch/create_alarm_modal_template.pt
- eucaconsole/templates/elbs/elb_wizard.pt
- eucaconsole/views/alarms.py
Implements https://eucalyptus.atlassian.net/browse/GUI-2544
Also fixes:
- https://eucalyptus.atlassian.net/browse/GUI-2570
- https://eucalyptus.atlassian.net/browse/GUI-2573
> GUI-2544: Implement copy alarm dialog on alarms landing page

- setup.py
replace python-crypto with pycryptopp
> Fix for GUI-1659

- eucaconsole/static/css/eucaconsole.css
- eucaconsole/static/css/pages/alarm-detail.css
- eucaconsole/static/css/pages/alarms.css
- eucaconsole/static/css/pages/elb_monitoring.css
- eucaconsole/static/css/pages/instance_monitoring.css
- eucaconsole/static/css/pages/metrics.css
- eucaconsole/static/css/pages/scalinggroup_monitoring.css
- eucaconsole/static/css/pages/scalinggroup_policy.css
- eucaconsole/static/css/pages/volume_monitoring.css
- eucaconsole/static/css/widgets/alarm-actions.css
- eucaconsole/static/css/widgets/create-alarm-dialog.css
- eucaconsole/static/js/pages/alarms/alarm_detail.js
- eucaconsole/static/js/services/scaling-groups-service.js
- eucaconsole/static/js/widgets/alarm-actions-editor/alarm-actions-editor.js
- eucaconsole/static/js/widgets/create-alarm-modal/create-alarm.js
- eucaconsole/static/sass/includes/_eucavariables.scss
- eucaconsole/static/sass/pages/alarm-detail.scss
- eucaconsole/static/sass/widgets/alarm-actions.scss
- eucaconsole/static/sass/widgets/create-alarm-dialog.scss
- eucaconsole/templates/cloudwatch/alarm_actions.pt
- eucaconsole/templates/cloudwatch/alarms_detail.pt
- eucaconsole/templates/cloudwatch/create_alarm_modal_template.pt
- eucaconsole/views/alarms.py
- eucaconsole/views/panels.py
https://eucalyptus.atlassian.net/browse/GUI-2530
> GUI-2530, alarm actions editor validation

- eucaconsole/forms/launchconfigs.py
- eucaconsole/templates/launchconfigs/launchconfig_create_more.pt
- eucaconsole/views/launchconfigs.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-2378
> GUI-2378: Avoid 500 error when creating a launch config like one with an image that's no longer available

- eucaconsole/static/js/pages/elb_wizard.js
- eucaconsole/templates/elbs/elb_wizard.pt
Fixes https://eucalyptus.atlassian.net/browse/GUI-2448
> GUI-2448: Fix security group selection in ELB wizard on VPC clouds

- eucaconsole/static/css/pages/stacks.css
- eucaconsole/static/js/pages/stack.js
- eucaconsole/static/sass/pages/stacks.scss
- eucaconsole/templates/stacks/stack_view.pt
- eucaconsole/templates/stacks/stacks.pt
- eucaconsole/views/stacks.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-2582
> GUI-2582: Fix CF stack status colors on details page Events tab

- eucaconsole/routes.py
- eucaconsole/static/js/services/alarm-service.js
- eucaconsole/static/js/widgets/create-alarm-modal/create-alarm.js
- eucaconsole/views/alarms.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-2557
> GUI-2557: Fix alarm name collision check in create alarm dialog

- eucaconsole/static/js/pages/scalinggroup_history.js
- eucaconsole/templates/scalinggroups/scalinggroup_history.pt
https://eucalyptus.atlassian.net/browse/GUI-2374
> GUI-2374 added infinite scroll

- eucaconsole/static/js/widgets/create-alarm-modal/create-alarm.js
- eucaconsole/views/alarms.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-2593
> GUI-2593: Include scaling group dimension choices for alarms with AWS/AutoScaling namespace

- eucaconsole/static/html/directives/instance_selector.html
- eucaconsole/static/js/widgets/instance_selector.js
- eucaconsole/templates/elbs/elb_instances.pt
- eucaconsole/views/elbs.py
- tests/elbs/test_elbs.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-2566
> GUI-2566: Prevent scaling group instance deselection on ELB Instances page when ELB is registered with the scaling group

- eucaconsole/views/alarms.py
https://eucalyptus.atlassian.net/browse/GUI-2599
> GUI-2599 implement alarm landing facets

- eucaconsole/static/js/widgets/alarm-actions-editor/alarm-actions-editor.js
Fixes https://eucalyptus.atlassian.net/browse/GUI-2530
> GUI-2530: Additional logic to enable Add Action button in actions editor for create alarm dialog on resource monitoring pages

- eucaconsole/tweens.py
- tests/tweens/test_tweens.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-2214
> GUI-2214: Better naming of standard response headers

- eucaconsole/static/css/pages/accounts.css
- eucaconsole/static/css/pages/alarm_history.css
- eucaconsole/static/css/pages/alarms.css
- eucaconsole/static/css/pages/bucket_contents.css
- eucaconsole/static/css/pages/buckets.css
- eucaconsole/static/css/pages/elb.css
- eucaconsole/static/css/pages/elbs.css
- eucaconsole/static/css/pages/groups.css
- eucaconsole/static/css/pages/images.css
- eucaconsole/static/css/pages/instance.css
- eucaconsole/static/css/pages/instance_types.css
- eucaconsole/static/css/pages/instances.css
- eucaconsole/static/css/pages/ipaddresses.css
- eucaconsole/static/css/pages/keypairs.css
- eucaconsole/static/css/pages/launchconfigs.css
- eucaconsole/static/css/pages/metrics.css
- eucaconsole/static/css/pages/roles.css
- eucaconsole/static/css/pages/scalinggroup.css
- eucaconsole/static/css/pages/scalinggroups.css
- eucaconsole/static/css/pages/securitygroups.css
- eucaconsole/static/css/pages/snapshots.css
- eucaconsole/static/css/pages/stack.css
- eucaconsole/static/css/pages/stacks.css
- eucaconsole/static/css/pages/user.css
- eucaconsole/static/css/pages/users.css
- eucaconsole/static/css/pages/volume.css
- eucaconsole/static/css/pages/volumes.css
- eucaconsole/static/sass/includes/_landingpage.scss
Fixes https://eucalyptus.atlassian.net/browse/GUI-2574
> GUI-2574: Better alignment of row-level actions menu icon in table view on landing pages

- eucaconsole/static/js/pages/alarms/alarm_detail.js
- eucaconsole/templates/cloudwatch/alarms_detail.pt
https://eucalyptus.atlassian.net/browse/GUI-2551
> GUI-2551, prevent expression interpolation in values returned from api.

- eucaconsole/templates/launchconfigs/launchconfig_wizard.pt
https://eucalyptus.atlassian.net/browse/GUI-2220
> GUI-2220 fixed security group alignment

- eucaconsole/views/stacks.py
https://eucalyptus.atlassian.net/browse/GUI-2274
> GUI-2274 narrowed comparison so EIPAssociation isn't caught in EIP test

- eucaconsole/cf-templates/Euca Stacks/LoadBalanced AutoScaling Web Application.json
- eucaconsole/views/stacks.py
https://eucalyptus.atlassian.net/browse/GUI-2563
> GUI-2563 converted to cfn-init, introduced auto scaling policies and instance role

- eucaconsole/views/stacks.py
https://eucalyptus.atlassian.net/browse/GUI-2617
> GUI-2617 provide url for alarms in stack resources

- eucaconsole/views/__init__.py
https://eucalyptus.atlassian.net/browse/GUI-2596
> GUI-2596 ignore session-based dns_enabled on login

- eucaconsole/templates/master_layout.pt
Fixes https://eucalyptus.atlassian.net/browse/GUI-2607
> GUI-2607: Reference minified version of Angular in master template

- eucaconsole/forms/users.py
https://eucalyptus.atlassian.net/browse/GUI-2210
Includes a couple of minor PEP8 fixes.
> GUI-2210, default checkboxes to checked.

- eucaconsole/views/panels.py
https://eucalyptus.atlassian.net/browse/GUI-2226
Trivial... 1 review
> GUI-2226 updated placeholder text for share account

- eucaconsole/forms/scalinggroups.py
- eucaconsole/static/css/pages/scalinggroup_wizard.css
- eucaconsole/static/js/pages/scalinggroup_wizard.js
- eucaconsole/static/sass/pages/scalinggroup_wizard.scss
- eucaconsole/templates/scalinggroups/scalinggroup_wizard.pt
- eucaconsole/views/scalinggroups.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-2449
> GUI-2449: Allow configuration of scaling group termination policies in create scaling group wizard

- eucaconsole/templates/volumes/volumes.pt
https://eucalyptus.atlassian.net/browse/GUI-2434
> GUI-2434 changed tile size field label

- eucaconsole/templates/dialogs/instance_dialogs.pt
https://eucalyptus.atlassian.net/browse/GUI-2348
> GUI-2348 corrected extra slash

- eucaconsole/templates/instances/instance_volumes.pt
- eucaconsole/templates/snapshots/snapshots.pt
- eucaconsole/templates/volumes/volume_snapshots.pt
https://eucalyptus.atlassian.net/browse/GUI-2434
> GUI-2434 fixed GB label in 3 other places

- eucaconsole/static/css/eucaconsole.css
- eucaconsole/static/sass/eucaconsole.scss
- eucaconsole/templates/scalinggroups/scalinggroup_view.pt
Fixes https://eucalyptus.atlassian.net/browse/GUI-2509
> GUI-2509: Fix hover styles for expandos and links on detail pages

- eucaconsole/forms/elbs.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-2474
> GUI-2474: Avoid extending deprecated WTForms validator for custom ELB form validators

- eucaconsole/static/js/pages/landingpage.js
- eucaconsole/templates/cloudwatch/metrics.pt
- eucaconsole/views/metrics.py
https://eucalyptus.atlassian.net/browse/GUI-2609
> GUI-2609 retain selected items on table refresh

- eucaconsole/static/js/pages/alarms/alarm_history.js
- eucaconsole/static/js/services/alarm-service.js
- eucaconsole/templates/cloudwatch/alarms_history.pt
https://eucalyptus.atlassian.net/browse/GUI-2614
> GUI-2614 fixed facet and text filtering. fixed history reload and breadcrumbs

- eucaconsole/views/images.py
- eucaconsole/views/instances.py
- eucaconsole/views/scalinggroups.py
https://eucalyptus.atlassian.net/browse/GUI-2613
> GUI-2613 handle missing instances and scaling groups w/ 404

- eucaconsole/templates/instances/instances.pt
- eucaconsole/templates/volumes/volumes.pt
- tests/selenium/guiops/pages/instance/instance_lp.py
https://eucalyptus.atlassian.net/browse/GUI-2486
> GUI-2486 added missing monitor options on instance landing

- eucaconsole/static/js/pages/elb_instances.js
- eucaconsole/static/js/widgets/instance_selector.js
- eucaconsole/templates/elbs/elb_instances.pt
https://eucalyptus.atlassian.net/browse/GUI-2567
> GUI-2567 use more deterministic method to trigger checking of instances in elb

- eucaconsole/views/elbs.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-2624
> GUI-2624: Ensure scaling group instances aren't de-registered when updating ELB instances list on ELB details page

- eucaconsole/static/js/pages/elb_wizard.js
Fixes https://eucalyptus.atlassian.net/browse/GUI-2276
> GUI-2276: Prevent duplicate ELB creation in wizard on IE 11

- eucaconsole/views/alarms.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-2615
> GUI-2615: Sort alarm history by most recent timestamp

- eucaconsole/views/roles.py
https://eucalyptus.atlassian.net/browse/GUI-2622
> GUI-2622 handle * as principal in policy

- eucaconsole/static/css/widgets/tag-editor.css
- eucaconsole/static/js/jasmine-spec/tag-editor/spec_tag_editor.js
- eucaconsole/static/js/pages/custom_filters.js
- eucaconsole/static/js/widgets/tag-editor/tag-editor.js
- eucaconsole/static/sass/widgets/tag-editor.scss
- eucaconsole/templates/scalinggroups/scalinggroup_wizard.pt
- eucaconsole/templates/tag-editor/tag-editor.pt
https://eucalyptus.atlassian.net/browse/GUI-2603
> GUI-2603, update button scss mixin, tighten submit strictures.

- eucaconsole/static/css/pages/buckets.css
- eucaconsole/static/img/svg/bucket_shared.svg
- eucaconsole/static/img/svg/bucket_solo_green.svg
- eucaconsole/static/sass/pages/buckets.scss
…when viewed in IE.
Fixes https://eucalyptus.atlassian.net/browse/GUI-1692
> GUI-1692: Add preserveAspectRatio SVG attribute for better bucket icon placement on buckets landing page

- eucaconsole/static/js/pages/elb_wizard.js
- eucaconsole/static/js/widgets/instance_selector.js
https://eucalyptus.atlassian.net/browse/GUI-2344
> GUI-2344 stop improper event firing in watcher

- eucaconsole/templates/stacks/stacks.pt
https://eucalyptus.atlassian.net/browse/GUI-2402
> GUI-2402, add ellipsis filter to avoid overflow.

- eucaconsole/static/js/pages/alarms/alarm_history.js
- eucaconsole/templates/cloudwatch/alarms_detail.pt
- eucaconsole/templates/cloudwatch/alarms_history.pt
- eucaconsole/views/alarms.py
https://eucalyptus.atlassian.net/browse/GUI-2569
Prevents template injection on the alarm history page.
Fixes some HTML entity inelegance on history pages.
> GUI-2569, Prevent template injection - alarm history

- eucaconsole/views/stacks.py
https://eucalyptus.atlassian.net/browse/GUI-2630
https://eucalyptus.atlassian.net/browse/GUI-2631
> GUI-2630 GUI-2631 apply formatting when converting template. Allow instance tags

- eucaconsole/templates/elbs/elbs.pt
https://eucalyptus.atlassian.net/browse/GUI-2486
> GUI-2486 updated elb landing page

- eucaconsole/templates/volumes/volume_monitoring.pt
https://eucalyptus.atlassian.net/browse/GUI-2604
> GUI-2604 remove create alarm and attachment message for failed volume

- eucaconsole/static/css/eucaconsole.css
- eucaconsole/static/sass/eucaconsole.scss
Fixes https://eucalyptus.atlassian.net/browse/GUI-2329
> GUI-2329: Fix notification icon alignment on IE 10/11

- eucaconsole/static/css/pages/alarm-detail.css
- eucaconsole/static/css/pages/alarms.css
- eucaconsole/static/css/pages/elb_monitoring.css
- eucaconsole/static/css/pages/instance_monitoring.css
- eucaconsole/static/css/pages/metrics.css
- eucaconsole/static/css/pages/scalinggroup_monitoring.css
- eucaconsole/static/css/pages/scalinggroup_policy.css
- eucaconsole/static/css/pages/volume_monitoring.css
- eucaconsole/static/css/widgets/create-alarm-dialog.css
- eucaconsole/static/sass/includes/_eucavariables.scss
- eucaconsole/static/sass/pages/alarm-detail.scss
- eucaconsole/static/sass/widgets/create-alarm-dialog.scss
Fixes https://eucalyptus.atlassian.net/browse/GUI-2592
> GUI-2592: Hide alarm threshold label from legend and tooltip on alarm details page and in create/copy alarm dialog

- eucaconsole/templates/scalinggroups/scalinggroup_view.pt
Fixes https://eucalyptus.atlassian.net/browse/GUI-2423
> GUI-2423: Add existing isNotChanged check for Save Changes button enablement when scaling group details page is loaded

- eucaconsole/views/instances.py
https://eucalyptus.atlassian.net/browse/GUI-2651
> GUI-2651 reduce list of image ids for filter by de-duping

- eucaconsole/static/css/pages/cloudwatch_charts.css
- eucaconsole/static/js/pages/metrics.js
- eucaconsole/static/sass/pages/cloudwatch_charts.scss
https://eucalyptus.atlassian.net/browse/GUI-2649
> GUI-2649 djust overlay margin to allow events to hit button/menu. fixed _selected refs

- licenses/jasmine.txt
> Add license file for jasmine

- licenses/foundation-datepicker.txt
I suspect this got lost due to a race condition in pull requests back in 2014.
Fixes GUI-2653
> Add license file for foundation-datepicker

- eucaconsole/static/js/pages/metrics.js
https://eucalyptus.atlassian.net/browse/GUI-2658
> GUI-2658 replace object.assign with loop

- eucaconsole/static/html/help/console_create_scaling_group_membership.html
Please merge with existing help content for Scaling Group Create : Membership tab.
> DOC-1749: added content for enable monitoring.

- eucaconsole/static/html/help/console_scaling_group_scale_history.html
- eucaconsole/templates/scalinggroups/scalinggroup_history.pt
Please create link to new help file for Scaling Group > View Details > Scale History tab: console_scaling_group_scale_history.html
> DOC-1709: new help for scaling history.

- eucaconsole/static/js/pages/metrics.js
https://eucalyptus.atlassian.net/browse/GUI-2535
https://eucalyptus.atlassian.net/browse/GUI-2661
> GUI-2535 rely on resource name for sorting, not just id

- eucaconsole/static/css/pages/alarm-detail.css
- eucaconsole/static/css/pages/alarms.css
- eucaconsole/static/css/pages/elb_monitoring.css
- eucaconsole/static/css/pages/instance_monitoring.css
- eucaconsole/static/css/pages/metrics.css
- eucaconsole/static/css/pages/scalinggroup_monitoring.css
- eucaconsole/static/css/pages/scalinggroup_policy.css
- eucaconsole/static/css/pages/volume_monitoring.css
- eucaconsole/static/css/widgets/create-alarm-dialog.css
- eucaconsole/static/sass/widgets/create-alarm-dialog.scss
- eucaconsole/templates/cloudwatch/create_alarm_modal_template.pt
https://eucalyptus.atlassian.net/browse/GUI-2671
> GUI-2671, add hook for help on dialog, scroll for overflow (for now)

- conf/console.default.ini
- launcher.sh
https://eucalyptus.atlassian.net/browse/GUI-2675
> GUI-2675 switch to defining worker_class in startup script

- eucaconsole/views/stacks.py
https://eucalyptus.atlassian.net/browse/GUI-2688
> GUI-2688 check for parameters in template before trying to process them

- eucaconsole/static/html/help/console_update_stack_parameters.html
- eucaconsole/static/html/help/console_update_stack_template.html
- eucaconsole/templates/stacks/stack_update.pt
Please merge and create 2 new hooks for the Stack Update tabs:
- console_update_stack_template.html
- console_update_stack_parameters.html
> DOC-1806: New stack update Help content created.

- eucaconsole/static/js/pages/stack_update.js
https://eucalyptus.atlassian.net/browse/GUI-2696
> GUI-2696 take edited text and save that

- eucaconsole/views/stacks.py
https://eucalyptus.atlassian.net/browse/GUI-2694
> GUI-2694 adjustments to supported resource and properties for stack templates

- eucaconsole/templates/snapshots/snapshot_view.pt
https://eucalyptus.atlassian.net/browse/GUI-2697
> GUI-2697 fixed conditional around help

- eucaconsole/static/html/help/console_create_snapshot.html
Sorry my bad! Please merge fixed file.
> DOC-1547: fixed last step.

- README.rst
https://eucalyptus.atlassian.net/browse/GUI-2704
> GUI-2704 removed gevent refs since we no longer use it

- eucaconsole/static/css/pages/scalinggroup_wizard.css
- eucaconsole/static/sass/pages/scalinggroup_wizard.scss
- eucaconsole/templates/scalinggroups/scalinggroup_wizard.pt
Fixes https://eucalyptus.atlassian.net/browse/GUI-2650 (for 4.3.1)
> GUI-2650: Disable "Membership" tab in Create Scaling Group wizard until all required fields in first tab have been entered

- eucaconsole/views/stacks.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-2691 (for 4.3.1)
> GUI-2691: Populate availability zone choices when zone is a CF template parameter

- eucaconsole/forms/elbs.py
- eucaconsole/static/js/pages/elb_wizard.js
Fixes https://eucalyptus.atlassian.net/browse/GUI-2693 (for 4.3.1)
> GUI-2693: Preselect 'default' security group when creating a load balancer on a VPC cloud

- eucaconsole/templates/elbs/elb_wizard.pt
- eucaconsole/views/elbs.py
Fixes:
- https://eucalyptus.atlassian.net/browse/GUI-2719
- https://eucalyptus.atlassian.net/browse/GUI-2720
> GUI-2719, GUI-2720: Fix ELB security policy selection during load balancer creation and updates

- eucaconsole/views/images.py
https://eucalyptus.atlassian.net/browse/GUI-2746
> GUI-2746 clean up if bundling bucket does not exist

- eucaconsole/static/css/eucaconsole.css
- eucaconsole/static/css/pages/securitygroup.css
- eucaconsole/static/js/jasmine-spec/spec_securitygroup.js
- eucaconsole/static/js/pages/securitygroup.js
- eucaconsole/static/sass/pages/securitygroup.scss
- eucaconsole/templates/securitygroups/securitygroup_view.pt
- eucaconsole/views/__init__.py
- eucaconsole/views/elbs.py
- eucaconsole/views/securitygroups.py
- tests/securitygroups/test_securitygroups.py
Implements https://eucalyptus.atlassian.net/browse/GUI-2288 by incorporating new tag editor on Create Security Group page and details page
> GUI-2288: Switch to new tag editor on security group pages

- eucaconsole/static/js/jasmine-spec/spec_volume_snapshots.js
- eucaconsole/static/js/pages/volume_snapshots.js
- eucaconsole/templates/volumes/volume_snapshots.pt
- eucaconsole/views/volumes.py
Implements https://eucalyptus.atlassian.net/browse/GUI-2291
> GUI-2291: Incorporate new tag editor in Create Snapshot dialog on Volume Snapshots page

- eucaconsole/static/js/jasmine-spec/spec_snapshot.js
- eucaconsole/static/js/pages/snapshot.js
- eucaconsole/templates/snapshots/snapshot_view.pt
- eucaconsole/views/snapshots.py
Implements https://eucalyptus.atlassian.net/browse/GUI-2289
> GUI-2289: Incorporate new tag editor on Snapshot Details page

- eucaconsole/static/js/jasmine-spec/spec_login.js
- eucaconsole/static/js/pages/login.js
- eucaconsole/templates/login.pt
https://eucalyptus.atlassian.net/browse/GUI-2758
> GUI-2758 add logic to keep login buttons disabled unless forms populated

- eucaconsole/static/js/jasmine-spec/spec_instance.js
- eucaconsole/static/js/pages/instance.js
- eucaconsole/templates/instances/instance_view.pt
- eucaconsole/views/instances.py
Implements https://eucalyptus.atlassian.net/browse/GUI-2285
> GUI-2285: Incorporate new tag editor on instance details page

- eucaconsole/static/js/jasmine-spec/spec_login.js
- eucaconsole/static/js/pages/login.js
- eucaconsole/templates/login.pt
> Oct06 master 50master

- eucaconsole/static/js/pages/instance_launch.js
- eucaconsole/templates/instances/instance_launch.pt
- eucaconsole/templates/launchconfigs/launchconfig_wizard.pt
Fixes https://eucalyptus.atlassian.net/browse/GUI-2776
> GUI-2776: Fix VPC subnet choices in Launch Instance wizard for Angular 1.5 compatibility

- eucaconsole/static/js/pages/instance_launch.js
> GUI-2776: Remove errant empty block

- eucaconsole/static/js/pages/instance.js
- eucaconsole/static/js/pages/volume.js
Fixes https://eucalyptus.atlassian.net/browse/GUI-2780
> GUI-2780: Prevent action menu items on Instance and Volume details page from redirecting to Dashboard

- eucaconsole/static/js/jasmine-spec/spec_instance_volumes.js
- eucaconsole/static/js/pages/instance_volumes.js
- eucaconsole/templates/instances/instance_volumes.pt
Fixes https://eucalyptus.atlassian.net/browse/GUI-2765
> GUI-2765: Fix volume choices in Attach Volume dialog on Instance Volumes page for Angular 1.5 compatibility

- eucaconsole/static/css/widgets/tag-editor.css
- eucaconsole/static/js/jasmine-spec/spec_scalinggroup_wizard.js
- eucaconsole/static/js/pages/scalinggroup_wizard.js
- eucaconsole/static/sass/widgets/tag-editor.scss
- eucaconsole/templates/scalinggroups/scalinggroup_view.pt
- eucaconsole/templates/scalinggroups/scalinggroup_wizard.pt
- eucaconsole/templates/tag-editor/tag-editor.pt
- eucaconsole/views/scalinggroups.py
Implements https://eucalyptus.atlassian.net/browse/GUI-2287
> GUI-2287: Incorporate new tag editor in Create Scaling Group wizard

- eucaconsole/static/js/jasmine-spec/spec_instances.js
- eucaconsole/static/js/pages/instances.js
- eucaconsole/templates/dialogs/instance_dialogs.pt
Fixes https://eucalyptus.atlassian.net/browse/GUI-2779
> GUI-2779: Fix IP Address choices in Associate IP with Instance dialog for Angular 1.5 compatibility

- eucaconsole/static/html/help/console_bucket_detail.html
- eucaconsole/static/html/help/console_instance_detail.html
@dkavanagh: changes reviewed and approved. Please merge to 4.4 codebase. Thanks!
> DOC-1988: update to include enabling CORS.

- eucaconsole/static/html/help/console_create_bucket.html
changed one word: "applied" if all looks good, please merge; if not, I'll check back later. thanks!
> DOC-1996 first try console checkin (applied)

- eucaconsole/views/login.py
https://eucalyptus.atlassian.net/browse/GUI-2796
> Gui 2796 adjusted account menu label

- eucaconsole/static/js/pages/login.js
https://eucalyptus.atlassian.net/browse/GUI-2791
> Gui 2791 converted $.base64 ref to btoa

- eucaconsole/static/css/eucaconsole.css
- eucaconsole/static/css/pages/dashboard.css
- eucaconsole/static/sass/pages/dashboard.scss
Fixes https://eucalyptus.atlassian.net/browse/GUI-2773
> GUI-2773: Remove tile actions menu hover outline on dashboard

- eucaconsole/constants/permissions.py
- eucaconsole/static/css/eucaconsole.css
- eucaconsole/static/css/pages/dashboard.css
- eucaconsole/static/js/jasmine-spec/spec_iam_policy_wizard.js
- eucaconsole/static/js/pages/iam_policy_wizard.js
- eucaconsole/static/sass/pages/dashboard.scss
- eucaconsole/templates/policies/policy_generator.pt
- eucaconsole/views/login.py
latest 4.4 changes into 5.0-master
> Oct21 master 50master

- eucaconsole/routes.py
- eucaconsole/static/js/jasmine-spec/spec_reporting.js
- eucaconsole/static/js/pages/reporting.js
- eucaconsole/templates/master_layout.pt
- eucaconsole/templates/reporting/reporting.pt
- eucaconsole/templates/reporting/reporting_dashboard.pt
- eucaconsole/templates/reporting/reporting_preferences.pt
- eucaconsole/templates/reporting/reporting_reports.pt
- eucaconsole/views/reporting.py
- karma.conf.js
https://eucalyptus.atlassian.net/browse/GUI-2794
> GUI-2794 initial reporting page w/ tabs

- conf/console.default.ini
- eucaconsole/models/auth.py
- eucaconsole/views/login.py
https://eucalyptus.atlassian.net/browse/GUI-2740
> Allow override of 1 hour admin session timeout

- eucaconsole/templates/buckets/bucket_item_details.pt
- eucaconsole/templates/buckets/buckets.pt
- eucaconsole/templates/elbs/elb_view.pt
- eucaconsole/templates/master_layout.pt
https://eucalyptus.atlassian.net/browse/GUI-2767
> GUI-2767, add rel to anchors that open to target _blank

- tests/selenium/guiops/dialogs/instance_dialogs.py
https://eucalyptus.atlassian.net/browse/GUI-2786
> GUI-2786 re-worked name css selector

- eucaconsole/static/js/pages/bucket_details.js
- eucaconsole/static/js/widgets/tag-editor/tag-editor.js
- eucaconsole/templates/buckets/bucket_details.pt
- eucaconsole/views/buckets.py
- eucaconsole/views/images.py
- tests/buckets/test_buckets.py
https://eucalyptus.atlassian.net/browse/GUI-2738
> GUI-2738 bucket tagging in details page

- eucaconsole/static/js/pages/elb-wizard/advanced.js
- eucaconsole/static/js/pages/elb-wizard/general.js
- eucaconsole/static/js/pages/elb-wizard/main.js
- eucaconsole/static/js/pages/elb-wizard/navigation.js
- eucaconsole/static/js/pages/elb-wizard/network.js
- eucaconsole/static/js/pages/elb-wizard/wizard.js
- eucaconsole/templates/elbs/wizard/main.pt
- karma.conf.js
https://eucalyptus.atlassian.net/browse/GUI-2815
> GUI-2815, break up wizard into separate files.

- eucaconsole/forms/instances.py
- eucaconsole/routes.py
- eucaconsole/static/css/eucaconsole.css
- eucaconsole/static/css/pages/instance.css
- eucaconsole/static/css/pages/instance_launch.css
- eucaconsole/static/css/pages/instance_launch_more.css
- eucaconsole/static/js/jasmine-spec/spec_instance_launch_more.js
- eucaconsole/static/sass/pages/instance.scss
- eucaconsole/static/sass/pages/instance_launch.scss
- eucaconsole/static/sass/pages/instance_launch_more.scss
- eucaconsole/templates/instances/instance_launch.pt
- eucaconsole/templates/instances/instance_launch_more.pt
- eucaconsole/templates/instances/instance_view.pt
- eucaconsole/views/instances.py
- tests/instances/test_instances.py
Implements https://eucalyptus.atlassian.net/browse/GUI-2739
> GUI-2739: Instance Termination Protection

- Gruntfile.js
- eucaconsole/static/banners/js.banner.txt
- eucaconsole/templates/elbs/wizard/main.pt
- package.json
Clean up indentation of Gruntfile
Add concatenation capability
Concatenate files for ELB Wizard
https://eucalyptus.atlassian.net/browse/GUI-2821
> GUI-2821, Grunt file concatenation for elb-wizard.

- eucaconsole/constants/__init__.py
- setup.py
https://eucalyptus.atlassian.net/browse/GUI-2797
> GUI-2797: Add Ohio, Mumbai, and Seoul to AWS regions

- conf/console.default.ini
- eucaconsole/constants/__init__.py
- eucaconsole/layout.py
- tests/config/test_config.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-2839
Note the Ohio region was added in https://github.com/eucalyptus/eucaconsole/pull/2110
> GUI-2839: Allow US GovCloud region to be available as a configurable option

- eucaconsole/models/auth.py
https://eucalyptus.atlassian.net/browse/GUI-2846
> GUI-2846 set anon setting on sts connection to True

- conf/console.default.ini
- eucaconsole/views/login.py
https://eucalyptus.atlassian.net/browse/GUI-2828
> GUI-2828 set scopes required by globus for getting id_token

- eucaconsole/constants/__init__.py
- eucaconsole/forms/instances.py
- eucaconsole/forms/vpcs.py
- eucaconsole/layout.py
- eucaconsole/routes.py
- eucaconsole/static/css/eucaconsole.css
- eucaconsole/static/css/pages/vpcs.css
- eucaconsole/static/js/pages/vpcs.js
- eucaconsole/static/sass/pages/elbs.scss
- eucaconsole/static/sass/pages/vpcs.scss
- eucaconsole/templates/panels/top_nav.pt
- eucaconsole/templates/vpcs/vpcs.pt
- eucaconsole/views/vpcs.py
Implements https://eucalyptus.atlassian.net/browse/GUI-2823
> GUI-2823: Implement VPCs landing page

- eucaconsole/constants/__init__.py
- eucaconsole/models/auth.py
- tests/auth/test_login.py
https://eucalyptus.atlassian.net/browse/GUI-2847
> Gui 2847 add 2 regions, stop relying on regions in boto 

- eucaconsole/views/elbs.py
https://eucalyptus.atlassian.net/browse/GUI-2833
> GUI-2833 add title part for new wizard view

- eucaconsole/models/reporting.py
https://eucalyptus.atlassian.net/browse/GUI-2856
> GUI-2856 initial code to support getting/setting reporting prefs

- conf/nginx.conf
https://eucalyptus.atlassian.net/browse/GUI-2743
> GUI-2743 changed location of ssl cert files to avoid selinux warning

- eucaconsole/templates/login.pt
https://eucalyptus.atlassian.net/browse/GUI-2858
> GUI-2858 updated login template

- eucaconsole/models/reporting.py
- eucaconsole/static/js/pages/reporting_preferences.js
- eucaconsole/static/js/services/reporting-service.js
- eucaconsole/templates/reporting/reporting_preferences.pt
- eucaconsole/views/reporting.py
https://eucalyptus.atlassian.net/browse/GUI-2857
> GUI-2857 added support for user report access enablement flag

- eucaconsole/forms/__init__.py
- eucaconsole/forms/vpcs.py
- eucaconsole/routes.py
- eucaconsole/static/css/eucaconsole.css
- eucaconsole/static/css/pages/subnet.css
- eucaconsole/static/js/pages/subnet_view.js
- eucaconsole/static/js/services/instances-service.js
- eucaconsole/static/js/widgets/notify.js
- eucaconsole/static/sass/pages/subnet.scss
- eucaconsole/templates/instances/instance_view.pt
- eucaconsole/templates/instances/instances.pt
- eucaconsole/templates/macros.pt
- eucaconsole/templates/vpcs/subnet_view.pt
- eucaconsole/templates/vpcs/vpc_view.pt
- eucaconsole/templates/vpcs/vpcs.pt
- eucaconsole/views/instances.py
- eucaconsole/views/vpcs.py
- tests/vpcs/test_vpcs.py
Implements https://eucalyptus.atlassian.net/browse/GUI-2827
> GUI-2827: Implement Subnet Details page

- eucaconsole/forms/__init__.py
- eucaconsole/forms/instances.py
- eucaconsole/views/instances.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-2861 for 4.4
> GUI-2861: Remove errant ip_address field to allow updates for an instance without a public IP address

- eucaconsole/views/instances.py
https://eucalyptus.atlassian.net/browse/GUI-2682
> GUI-2682 check for missing image and report helpful error, not internal error

- eucaconsole/static/css/pages/iam_policy_wizard.css
- eucaconsole/static/sass/pages/iam_policy_wizard.scss
- eucaconsole/templates/policies/iam_policy_wizard.pt
Fixes https://eucalyptus.atlassian.net/browse/GUI-2875 (for 4.4)
> GUI-2875: Fix policy editor textarea position to keep it visible when page scrolls

- eucaconsole/forms/vpcs.py
- eucaconsole/routes.py
- eucaconsole/static/css/pages/subnet.css
- eucaconsole/static/css/widgets/route-table-editor.css
- eucaconsole/static/js/pages/subnet_view.js
- eucaconsole/static/js/widgets/route-table-editor.js
- eucaconsole/static/sass/pages/subnet.scss
- eucaconsole/static/sass/widgets/route-table-editor.scss
- eucaconsole/templates/vpcs/route-table-editor.pt
- eucaconsole/templates/vpcs/subnet_view.pt
- eucaconsole/templates/vpcs/vpc_view.pt
- eucaconsole/views/vpcs.py
https://eucalyptus.atlassian.net/browse/GUI-2855
Also adds 404 handlers to VPC and subnet detail pages
> GUI-2855: Implement create route table

- eucaconsole/forms/vpcs.py
- eucaconsole/routes.py
- eucaconsole/static/css/pages/internet_gateway.css
- eucaconsole/static/js/pages/internet_gateway_view.js
- eucaconsole/static/sass/pages/internet_gateway.scss
- eucaconsole/templates/vpcs/internet_gateway_view.pt
- eucaconsole/templates/vpcs/subnet_view.pt
- eucaconsole/templates/vpcs/vpc_view.pt
- eucaconsole/templates/vpcs/vpcs.pt
- eucaconsole/views/vpcs.py
https://eucalyptus.atlassian.net/browse/GUI-2830
> GUI-2830: Implement Internet Gateway details page

- setup.py
https://eucalyptus.atlassian.net/browse/GUI-2882
> GUI-2882 ease version num restriction on pandas to work properly on centos

- eucaconsole/forms/__init__.py
- eucaconsole/forms/vpcs.py
- eucaconsole/routes.py
- eucaconsole/static/css/pages/nat_gateway.css
- eucaconsole/static/css/pages/subnet.css
- eucaconsole/static/js/pages/nat_gateway_view.js
- eucaconsole/static/sass/pages/nat_gateway.scss
- eucaconsole/static/sass/pages/subnet.scss
- eucaconsole/templates/ipaddresses/ipaddress_view.pt
- eucaconsole/templates/ipaddresses/ipaddresses.pt
- eucaconsole/templates/vpcs/internet_gateway_view.pt
- eucaconsole/templates/vpcs/nat_gateway_view.pt
- eucaconsole/templates/vpcs/subnet_view.pt
- eucaconsole/views/__init__.py
- eucaconsole/views/ipaddresses.py
- eucaconsole/views/vpcs.py
Implements:
- https://eucalyptus.atlassian.net/browse/GUI-2870
- https://eucalyptus.atlassian.net/browse/GUI-2871
Fixes:
- https://eucalyptus.atlassian.net/browse/GUI-2868
> GUI-2870, GUI-2871: Create/View NAT Gateway

- .travis.yml
- eucaconsole/constants/permissions.py
- eucaconsole/templates/policies/policy_generator.pt
https://eucalyptus.atlassian.net/browse/GUI-2876
> GUI-2876: Add SQS actions to IAM policy editor

- .travis.yml
- eucaconsole/forms/instances.py
- eucaconsole/static/js/pages/instance.js
- eucaconsole/templates/instances/instance_view.pt
- eucaconsole/views/instances.py
Implements https://eucalyptus.atlassian.net/browse/GUI-2832
> GUI-2832: Allow security group(s) modification for VPC instances

- eucaconsole/static/css/pages/alarm_history.css
- eucaconsole/static/js/pages/alarms/alarm_history.js
- eucaconsole/static/sass/pages/alarm_history.scss
https://eucalyptus.atlassian.net/browse/GUI-2885
> GUI-2885 fixed alarm history initial data load

- eucaconsole/constants/cloudwatch.py
- eucaconsole/views/metrics.py
https://eucalyptus.atlassian.net/browse/GUI-2817
> GUI-2817 added SQS metrics in table and facets

- eucaconsole/static/js/pages/reporting_reports.js
- eucaconsole/templates/reporting/reporting_reports.pt
- eucaconsole/views/reporting.py
https://eucalyptus.atlassian.net/browse/GUI-2737
> GUI-2737 implemented programatic date range generation for select, use selected date for report

- eucaconsole/static/js/pages/iam_policy_wizard.js
- eucaconsole/templates/policies/policy_generator.pt
Also, remove SQS namespace check from userid/username condition keys.
https://eucalyptus.atlassian.net/browse/GUI-2887
> GUI-2887: Add principalType condition key to IAM policy generator

- eucaconsole/static/js/pages/account.js
- eucaconsole/static/js/pages/elb_wizard.js
- eucaconsole/static/js/pages/group.js
- eucaconsole/static/js/pages/instance.js
- eucaconsole/static/js/pages/instance_launch.js
- eucaconsole/static/js/pages/instance_volumes.js
- eucaconsole/static/js/pages/ipaddress.js
- eucaconsole/static/js/pages/keypair.js
- eucaconsole/static/js/pages/landingpage.js
- eucaconsole/static/js/pages/launchconfig.js
- eucaconsole/static/js/pages/launchconfig_wizard.js
- eucaconsole/static/js/pages/role.js
- eucaconsole/static/js/pages/scalinggroup.js
- eucaconsole/static/js/pages/scalinggroup_instances.js
- eucaconsole/static/js/pages/scalinggroup_policies.js
- eucaconsole/static/js/pages/scalinggroup_wizard.js
- eucaconsole/static/js/pages/securitygroup.js
- eucaconsole/static/js/pages/snapshot.js
- eucaconsole/static/js/pages/stack.js
- eucaconsole/static/js/pages/user_view.js
- eucaconsole/static/js/pages/volume.js
- eucaconsole/static/js/pages/volume_snapshots.js
https://eucalyptus.atlassian.net/browse/GUI-2774
> GUI-2774: Avoid auto-focusing on submit button in dialogs when opened

- .travis.yml
- eucaconsole/views/login.py
https://eucalyptus.atlassian.net/browse/GUI-2879
> GUI-2879 added more error checking and logging when oidc credentials ini file is badly constructed

- eucaconsole/static/js/pages/usage_reports.js
- eucaconsole/templates/reporting/usage_reports.pt
https://eucalyptus.atlassian.net/browse/GUI-2805
> GUI-2805 changed granularity values to match API requirements

- eucaconsole/static/js/widgets/modal.js
- eucaconsole/templates/dialogs/cloudwatch_chart_dialog.pt
https://eucalyptus.atlassian.net/browse/GUI-2884
> GUI-2884 allow multiple modals on 1 page, set large chart dialogs to auto-load data

- eucaconsole/static/css/eucaconsole.css
- eucaconsole/static/css/pages/bucket_contents.css
- eucaconsole/static/css/pages/elb_wizard.css
- eucaconsole/static/css/pages/iam_policy_wizard.css
- eucaconsole/static/css/pages/instance.css
- eucaconsole/static/css/pages/instance_launch.css
- eucaconsole/static/css/pages/instance_launch_more.css
- eucaconsole/static/css/pages/launchconfig_wizard.css
- eucaconsole/static/css/pages/login.css
- eucaconsole/static/css/pages/scalinggroup_wizard.css
- eucaconsole/static/css/pages/stack_update.css
- eucaconsole/static/css/pages/stack_wizard.css
- eucaconsole/static/css/widgets/tag-editor.css
- eucaconsole/static/sass/eucaconsole.scss
- eucaconsole/static/sass/includes/_eucavariables.scss
- eucaconsole/static/sass/pages/bucket_contents.scss
- eucaconsole/static/sass/pages/iam_policy_wizard.scss
- eucaconsole/static/sass/pages/instance.scss
- eucaconsole/static/sass/pages/instance_launch_more.scss
- eucaconsole/static/sass/widgets/tag-editor.scss
- eucaconsole/templates/instances/instance_launch_more.pt
- eucaconsole/views/cloudwatchapi.py
https://eucalyptus.atlassian.net/browse/GUI-2896
> GUI-2896: More rebranding tweaks

- eucaconsole/models/reporting.py
- eucaconsole/routes.py
- eucaconsole/static/css/pages/reporting.css
- eucaconsole/static/js/pages/instance_usage.js
- eucaconsole/static/js/pages/reporting_reports.js
- eucaconsole/static/js/pages/usage_reports.js
- eucaconsole/static/js/services/reporting-service.js
- eucaconsole/static/sass/pages/reporting.scss
- eucaconsole/templates/reporting/instance_usage.pt
- eucaconsole/templates/reporting/reporting_reports.pt
- eucaconsole/templates/reporting/usage_reports.pt
- eucaconsole/views/reporting.py
https://eucalyptus.atlassian.net/browse/GUI-2737
> Gui 2737 implement ec2 usage reports. 

- eucaconsole/static/css/widgets/tag-editor.css
- eucaconsole/static/sass/widgets/tag-editor.scss
- eucaconsole/templates/tag-editor/tag-editor.pt
Minor style fix for 4.4.1 rebranding
https://eucalyptus.atlassian.net/browse/GUI-2896
> GUI-2896: Make tag editor styles consistent with other tag-like styles

- eucaconsole/static/js/services/bucket-cors-service.js
- eucaconsole/views/buckets.py
https://eucalyptus.atlassian.net/browse/GUI-2894
> GUI-2894: Pass CSRF token in request body

- eucaconsole/static/js/services/bucket-policy-service.js
- eucaconsole/views/buckets.py
https://eucalyptus.atlassian.net/browse/GUI-2910
> GUI-2910: Pass CSRF token in request body

- eucaconsole/templates/cloudwatch/create_alarm_modal_template.pt
https://eucalyptus.atlassian.net/browse/GUI-2732
https://eucalyptus.atlassian.net/browse/GUI-2734
> GUI-2732, GUI-2734: Allow positive numbers less than 1 for threshold values in create alarm dialog

- eucaconsole/forms/vpcs.py
- eucaconsole/routes.py
- eucaconsole/static/css/pages/subnet.css
- eucaconsole/static/css/pages/vpc.css
- eucaconsole/static/js/pages/network_acl_view.js
- eucaconsole/static/sass/pages/subnet.scss
- eucaconsole/static/sass/pages/vpc.scss
- eucaconsole/templates/vpcs/network_acl_view.pt
- eucaconsole/templates/vpcs/subnet_view.pt
- eucaconsole/templates/vpcs/vpc_view.pt
- eucaconsole/views/vpcs.py
https://eucalyptus.atlassian.net/browse/GUI-2891
> GUI-2891: Network ACL details page WIP

- .travis.yml
- eucaconsole/forms/__init__.py
- eucaconsole/forms/vpcs.py
- eucaconsole/routes.py
- eucaconsole/static/js/pages/network_acl_new.js
- eucaconsole/static/js/pages/network_acl_view.js
- eucaconsole/templates/vpcs/network_acl_new.pt
- eucaconsole/templates/vpcs/network_acl_view.pt
- eucaconsole/templates/vpcs/subnet_view.pt
- eucaconsole/templates/vpcs/vpc_view.pt
- eucaconsole/views/vpcs.py
- setup.py
https://eucalyptus.atlassian.net/browse/GUI-2890
https://eucalyptus.atlassian.net/browse/GUI-2916
> GUI-2890, GUI-2916: Implement Create/Delete Network ACL and allow modification of subnet-NACL associations

- eucaconsole/static/js/pages/bucket_details.js
- eucaconsole/templates/buckets/bucket_details.pt
https://eucalyptus.atlassian.net/browse/GUI-2914
> GUI-2914 fixed policy reset if dialog dismissed, cleaned up other items

- .travis.yml
- eucaconsole/static/js/widgets/create-alarm-modal/create-alarm.js
- setup.py
https://eucalyptus.atlassian.net/browse/GUI-2913
> Gui 2913 set initial threshold, graph renders by default

- eucaconsole/static/js/pages/usage_reports.js
- eucaconsole/templates/reporting/usage_reports.pt
https://eucalyptus.atlassian.net/browse/GUI-2805
> GUI-2805 updated usage types
