- eucaconsole/forms/images.py
- eucaconsole/views/images.py
- tests/auth/test_changepassword.py
- tests/images/test_images.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-1551
> GUI-1551: Escape double curly braces in image description field on image details page

- eucaconsole/templates/instances/instance_launch.pt
- eucaconsole/views/instances.py
EUCA-10308 modified how the addressing_type param is accepted, rejecting 'private' when a VPC instance is launch.  This fix accounts for the updated behavior.
https://eucalyptus.atlassian.net/browse/GUI-1579
Note: Do not merge this unless GUI-1579 is scoped for 4.1
> GUI-1579: Don't pass addressing_type when launching VPC instances on Eucalyptus

- eucaconsole/static/js/pages/landingpage.js
handle smart-refresh better with multiple getItems() callers
https://eucalyptus.atlassian.net/browse/GUI-1590
The changes are these:
add state variable to indicate smart refresh is already happening, so we can avoid starting a new one.
reset that variable when no state requiring smart refresh is in the table
pass optional value into getItems() so that we can know when it was called from existing smart refresh timeout
This works well. It refreshes properly with no filters. As filters are added, the single refresh timeout is the only one running and the new filters are used. If the transient item is filtered out, smart refresh halts after the next cycle. If a transient item is brought back in by a filter change, smart refresh initiates properly again. This change fixes the mult-fetch …
> GUI-1590 handle smart-refresh better with multiple getItems() callers

- eucaconsole/views/launchconfigs.py
allow for instance profile names that aren't an ARN
https://eucalyptus.atlassian.net/browse/GUI-1575
> GUI-1575 allow for instance profile names that aren't an ARN

- eucaconsole/static/js/pages/instances.js
- eucaconsole/templates/dialogs/instance_dialogs.pt
- eucaconsole/views/instances.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-1608
> GUI-1608: Reference instance IP rather than FQDN in Connect to Instance dialog's SSH instructions

- eucaconsole/forms/securitygroups.py
- eucaconsole/templates/securitygroups/securitygroup_view.pt
- tests/securitygroups/test_securitygroups.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-1643
Security group name/description restrictions are documented at http://docs.aws.amazon.com/cli/latest/reference/ec2/create-security-group.html
> GUI-1643: Disallow non-ASCII chars in security group description for API compatibility

- eucaconsole/static/js/pages/instance_launch.js
- eucaconsole/static/js/pages/launchconfig_wizard.js
- eucaconsole/templates/dialogs/create_keypair_dialog.pt
Fixes https://eucalyptus.atlassian.net/browse/GUI-1642
> GUI-1642: Prevent non-ASCII chars and slashes for key pair name when created via launch wizards

- eucaconsole/forms/securitygroups.py
- eucaconsole/templates/dialogs/create_securitygroup_dialog.pt
Also add validation constraint to create security group dialog on launch wizards.
References https://eucalyptus.atlassian.net/browse/GUI-1643
> GUI-1643: Specify which characters are valid in security group description

- eucaconsole/static/css/eucaconsole.css
- eucaconsole/static/sass/eucaconsole.scss
Fixes https://eucalyptus.atlassian.net/browse/GUI-1662
Tested on latest Firefox, Safari, Chrome, IE 10, and IE 11
> GUI-1662: Remove errant padding-top to fix alignment of read-only fields on detail pages

- eucaconsole/static/css/eucaconsole.css
- eucaconsole/static/sass/eucaconsole.scss
https://eucalyptus.atlassian.net/browse/GUI-1671
Marked top padding important for has-actions panels
> GUI-1671 Marked top padding important for has-actions panels

- eucaconsole/static/js/pages/bucket_contents.js
- eucaconsole/static/js/pages/bucket_details.js
- eucaconsole/static/js/pages/bucket_upload.js
Fixes https://eucalyptus.atlassian.net/browse/GUI-1687
Tested on Safari 8 (OS X Yosemite), Firefox 37 (OS X), and IE 11.
Note that IE 11 displays errant behavior for the post-upload action, and this PR (or the Angular/Foundation updates) neither caused nor fixes the new issue tracked in https://eucalyptus.atlassian.net/browse/GUI-1690
> GUI-1687: Fix S3 file upload behavior broken by Angular and Foundation updates

- eucaconsole/templates/launchconfigs/launchconfig_view.pt
Fixes https://eucalyptus.atlassian.net/browse/GUI-1683
> GUI-1683: Display horizontal rule above storage area only for launch configs that have a BDM

- eucaconsole/templates/scalinggroups/scalinggroup_policies.pt
- eucaconsole/templates/scalinggroups/scalinggroup_policy.pt
- eucaconsole/views/scalinggroups.py
Also fix alignment of alarm field on Create Scaling Policy page.
Fixes https://eucalyptus.atlassian.net/browse/GUI-1694
> GUI-1694: Support unicode chars in scaling policy name

- eucaconsole/static/css/eucaconsole.css
- eucaconsole/static/sass/eucaconsole.scss
Fixes https://eucalyptus.atlassian.net/browse/GUI-1669
Tested on IE 10 and 11 (Windows 7 64-bit).
Spot-checked on Safari 8, Firefox 37, and Chrome 42 on Mac OS 10.10
> GUI-1669: Defer to Foundation to set input field height and line height

- eucaconsole/templates/dashboard.pt
- eucaconsole/templates/groups/group_view.pt
- eucaconsole/templates/managecredentials.pt
- eucaconsole/templates/roles/role_view.pt
- eucaconsole/templates/stacks/stack_wizard.pt
Also minor HTML attribute cleanup to use double quotes for consistency.
Fixes https://eucalyptus.atlassian.net/browse/GUI-1737
> GUI-1737: Replace i18n:translate with i18n:attributes where appropriate

- setup.py
Pull request #1405 made setup.py require boto 2.38.0 with an `==` comparison rather than a `>=`, which could make eucaconsole stop running entirely if a distro/EPEL/etc updates boto past that version.  That is probably not the experience we're looking for, so this commit switches that to `>=` instead.
> Require a minimum boto version, not a precise one

- eucaconsole/forms/__init__.py
- eucaconsole/static/js/pages/stack_wizard.js
- eucaconsole/templates/stacks/stack_wizard.pt
- eucaconsole/views/stacks.py
ignore image params when FindInMap is found and referenced map contains any emi- reference. Also don't perform aws check on sample templates
https://eucalyptus.atlassian.net/browse/GUI-1885
> GUI-1885 improve image param checking in aws templates

- eucaconsole/static/js/pages/stack_wizard.js
fixed showing of next-button after aws template we can't use detected
https://eucalyptus.atlassian.net/browse/GUI-1914
> GUI-1914 fixed showing of next-button after aws template we can't use detected

- eucaconsole/static/css/eucaconsole.css
- eucaconsole/static/sass/eucaconsole.scss
- eucaconsole/templates/dialogs/instance_dialogs.pt
Also fix modal dialog title left margin/alignment issue.
https://eucalyptus.atlassian.net/browse/GUI-1640
> GUI-1640: Display relevant instructions for non-Windows instances when launched without a key pair

- eucaconsole/models/auth.py
allow for dns login request to raise exceptions related to auth failures
https://eucalyptus.atlassian.net/browse/GUI-1944
> GUI-1944 allow for dns login request to raise exceptions related to auth failures

- eucaconsole/models/auth.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-1976
> GUI-1976: Better handling of missing error message when the ufshost is unreachable on login attempts

- conf/nginx.conf
Since $server_name is, by default, set to localhost, update the rewrite directive to point to $hostname instead.  The administrator could, however, specify $server_name explicitly if needs be.  This seems more flexible.  We may want to document this.
> GUI-1958 Set rewrite target to $hostname instead of $server_name.

- eucaconsole/views/cloudwatchapi.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-2001
> GUI-2001: Avoid 500 error on Instance Monitoring page with empty data sets for charts that auto-collapse to KB/MB/GB

- eucaconsole/views/buckets.py
catch errors in bucket access for shared buckets,
override boto's double-slash default behavior for bucket item details page
https://eucalyptus.atlassian.net/browse/GUI-1993
https://eucalyptus.atlassian.net/browse/GUI-1994
> GUI-1994, GUI-1993 better shared bucket error handling, better double-slash handling.

- conf/console.default.ini
- eucaconsole/views/login.py
...also set session.secure = true in the default console.ini file
Fixes https://eucalyptus.atlassian.net/browse/GUI-1565
> GUI-1565: Remove misleading warning when session.secure = false and console is requested via HTTPS

- conf/console.default.ini
- eucaconsole/views/__init__.py
added setting to selectively disable image caching on eucalyptus clouds (not aws)
https://eucalyptus.atlassian.net/browse/GUI-1889
> GUI-1889 added setting to selectively disable image caching on eucalyptus clouds (not aws)

- eucaconsole/static/css/pages/cloudwatch_charts.css
- eucaconsole/static/js/pages/cloudwatch_charts.js
- eucaconsole/static/sass/pages/cloudwatch_charts.scss
- eucaconsole/templates/elbs/elb_monitoring.pt
- eucaconsole/templates/instances/instance_monitoring.pt
Also prevent old chart from lingering in large chart modal when transitioning to empty chart message on duration change.
Fixes https://eucalyptus.atlassian.net/browse/GUI-2031
> GUI-2031: Prevent empty data message from lingering when chart data is returned on duration modification

- eucaconsole/static/css/widgets/instance_selector.css
- eucaconsole/static/html/directives/instance_selector.html
- eucaconsole/static/sass/widgets/instance_selector.scss
- eucaconsole/templates/elbs/elb_instances.pt
…also fix background color of labels for instances in stopped state when listed in ELB instance selector, and remove errant tooltip on ELB instance status hover.
Fixes https://eucalyptus.atlassian.net/browse/GUI-2037
> GUI-2037: Convert "unhealthy" to "out of service" in zone/subnet tiles on ELB Instances page

- eucaconsole/views/elbs.py
…Also remove unused form field code for bucket name choices.
Fixes https://eucalyptus.atlassian.net/browse/GUI-2077
> GUI-2077: Prevent unexpected "S3Bucket name cannot be empty" error when creating an ELB without access logs on AWS

- eucaconsole/views/scalinggroups.py
- tests/scalinggroups/test_scalinggroups.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-2084
- Avoid stringifying metric-unit mapping twice, allowing relevant units to display when metric is selected in the Create Alarm dialog on the ASG scaling policy page;  
- Add unit test for create alarm dialog
> GUI-2084: Fix display of metric-relevant units in Create Alarm dialog

- eucaconsole/static/js/pages/base_elb_wizard.js
- eucaconsole/static/js/pages/elb_view.js
- eucaconsole/static/js/pages/elb_wizard.js
- eucaconsole/static/js/widgets/elb_security_group_warning_dialog.js
- eucaconsole/templates/dialogs/elb_security_group_warning_dialog.pt
- eucaconsole/templates/elbs/elb_view.pt
- eucaconsole/templates/elbs/elb_wizard.pt
- eucaconsole/views/dialogs.py
- eucaconsole/views/elbs.py
- tests/elbs/test_elbs.py
Implements the following for https://eucalyptus.atlassian.net/browse/GUI-2024 (for VPC clouds)...
- If the selected security groups don't contain rules that open required ports for the listeners or health check when creating an ELB, display a warning dialog notifying the user to open the relevant ports in the listed security group(s).  The modal dialog is displayed when clicking the "Create Load Balancer" button.
- The ELB detail page (General tab) also implements the above when the "Save Changes" button is clicked.
> GUI-2024: Display warning dialog when ELB security group rules don't cover listener and health check ports

- eucaconsole/views/scalinggroups.py
Potentially fixes https://eucalyptus.atlassian.net/browse/GUI-2126
> GUI-2126: Remove errant scaling group dimension when adding a scaling policy to allow ELB alarms to work

- eucaconsole/views/elbs.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-2174
> GUI-2174: Properly configure bucket access ACLs even when the prefix is blank

- eucaconsole/static/css/widgets/tag-editor.css
- eucaconsole/static/js/pages/scalinggroup.js
- eucaconsole/static/js/widgets/tag-editor/tag-editor.js
- eucaconsole/static/sass/widgets/tag-editor.scss
- eucaconsole/templates/scalinggroups/scalinggroup_view.pt
- eucaconsole/templates/tag-editor/tag-editor.pt
- eucaconsole/views/scalinggroups.py
* Minor changes to tag-editor directive to better integrate into form-level validation.
* Parameterize tag-editor for autoscale.
* Create chosen directive to allow the chosen library to better integrate with angular and actually work with angular form validation.  This will move to it's own module in the next integration PR.
* Update template to inject form data into angular-land.
> GUI-2286 Complete integration of tag editor into scaling group view

- eucaconsole/views/launchconfigs.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-2376
> GUI-2376: Avoid 500 error on launch configs landing page when the image mapping lookup fails

- eucaconsole/views/snapshots.py
- tests/snapshots/test_snapshots.py
… also remove problematic unit test.
Fixes https://eucalyptus.atlassian.net/browse/GUI-2415
> GUI-2415: Revert to passing volume ids via filters to prevent errors w.r.t. missing volumes

- eucaconsole/templates/instances/instance_volumes.pt
…also hide "Detach" action if volume is still in attaching state.
Fixes https://eucalyptus.atlassian.net/browse/GUI-2420
> GUI-2420: Hide errant "Monitor" action in volume tile on instance-volumes page

- eucaconsole/constants/cloudwatch.py
- eucaconsole/forms/alarms.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-2257 (for 4.2.2)
> GUI-2257: Prevent validation error for unit field when creating alarms for ASG metrics

- eucaconsole/config.py
- eucaconsole/forms/__init__.py
- eucaconsole/models/auth.py
https://eucalyptus.atlassian.net/browse/GUI-2473
Something to note here: Due to a new value added to the connection in boto, we could no longer pickle the boto value objects. That led to cleaning up values from them we shouldn't cache anyway, mostly connection and region. That's a net gain which also fixed a problem.
> GUI-2473 when back-end ssl cert validation turned off, disable checking in python

- eucaconsole/models/auth.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-2497
> GUI-2497: Guard against missing ssl unverified context method to support Python < 2.7.9

- eucaconsole/constants/__init__.py
… on AWS and multi-region Eucalyptus clouds
Fixes https://eucalyptus.atlassian.net/browse/GUI-2545
> GUI-2545: Fix CloudWatch route name references to avoid 500 error when switching regions

- eucaconsole/templates/cloudwatch/alarms_detail.pt
...also avoids breaking statistic selection on non-English console deployments.
Fixes https://eucalyptus.atlassian.net/browse/GUI-2572
> GUI-2572: Ensure an alarm with statistic = SampleCount displays the proper statistic on the alarm details page

- eucaconsole/views/instances.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-2362
> GUI-2362: Avoid 500 error when stopping an EBS-backed instance launched from a subsequently deregistered image

- eucaconsole/templates/instances/instance_view.pt
Fixes https://eucalyptus.atlassian.net/browse/GUI-2400
> GUI-2400: Avoid displaying instance type field twice for EBS-backed instances on details page

- eucaconsole/views/elbs.py
…also move scaling groups API call within boto error handler.
Fixes https://eucalyptus.atlassian.net/browse/GUI-2626
> GUI-2626: Avoid 500 error when manually selecting zero non-ASG instances on ELB instances page

- eucaconsole/views/stacks.py
https://eucalyptus.atlassian.net/browse/GUI-2635
> GUI-2635 removed NetworkInterfaceAttachment from unsupported list

- eucaconsole/static/css/pages/scalinggroup.css
- eucaconsole/static/sass/pages/scalinggroup.scss
Fixes cross-browser styling issue for https://eucalyptus.atlassian.net/browse/GUI-2543
> GUI-2543: Avoid threshold/dimensions nowrap styling in scaling policies table to avoid breaking outside of container

- conf/nginx.conf
SELinux does not normally allow HTTP daemons to write logs outside of their own log directories.  While we could technically start allowing that for our purposes, it would be safer to simply move where we put our nginx log files.
This does not affect eucaconsole.log.
This fixes [GUI-2708](https://eucalyptus.atlassian.net/browse/GUI-2708).
> GUI-2708:  Move nginx log files to /var/log/nginx

- eucaconsole/templates/scalinggroups/scalinggroup_monitoring.pt
Fixes https://eucalyptus.atlassian.net/browse/GUI-2660
> GUI-2660: Pass full metric namespace when refreshing charts on scaling group monitoring page

- conf/console.default.ini
- eucaconsole/views/__init__.py
- tests/config/test_config.py
Implements https://eucalyptus.atlassian.net/browse/GUI-2745 (for 4.4)
> GUI-2745: Disable EC2 image cache by default on Eucalyptus clouds

- eucaconsole/static/js/jasmine-spec/spec_instance_create_image.js
- eucaconsole/templates/instances/instance_create_image.pt
- eucaconsole/views/instances.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-2778
> GUI-2778: Fix bucket choices in Create Image from Instance page for Angular 1.5 compatibility

- eucaconsole/static/js/pages/scalinggroup_wizard.js
- eucaconsole/templates/instances/instance_launch.pt
- eucaconsole/templates/scalinggroups/scalinggroup_wizard.pt
Also, fix display of VPC network/subnet choices in summary area of launch instance wizard.
https://eucalyptus.atlassian.net/browse/GUI-2777
> GUI-2777: Fix VPC subnet choices in scaling group wizard for Angular 1.5 compatibility

- eucaconsole/forms/angularcompat.py
- eucaconsole/forms/elbs.py
- eucaconsole/static/js/pages/elb_wizard.js
- eucaconsole/templates/elbs/elb_wizard.pt
- eucaconsole/views/elbs.py
- tests/__init__.py
- tests/elbs/test_elbs.py
- tests/utils/test_angularcompat.py
Fixes https://eucalyptus.atlassian.net/browse/GUI-2784
> GUI-2784: Fix ELB Wizard form field choices for Angular 1.5 compatibility

- eucaconsole/layout.py
- eucaconsole/views/dashboard.py
- eucaconsole/views/regions.py
Also, prevent duplicate "US GovCloud" entries from displaying in region choices.
https://eucalyptus.atlassian.net/browse/GUI-2839
> GUI-2839: Allow broken cookie to be cleared (following console restart) when GovCloud region is mistakenly enabled

- eucaconsole/static/css/pages/iam_policy_wizard.css
- eucaconsole/static/sass/pages/iam_policy_wizard.scss
Follow-up fix for https://eucalyptus.atlassian.net/browse/GUI-2875
Note that with the additional media query, GUI-2875 is addressed only when the viewport is tall enough to display the entire policy editor preview area.
> GUI-2875: Fix policy preview area position only when viewport height is tall enough to display Create Policy button

- eucaconsole/static/html/help/console_bucket_detail.html
- eucaconsole/static/html/help/console_instance_detail.html
DOC-2125: docs.hpcloud.com links removed from 2 online help files. No new hyperlinks created at this time.
> DOC-2125: remove docs.hpcloud.com links from online help
